import { randomUUID } from 'node:crypto';
import '@fastify/websocket';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { WebSocket } from 'ws';
import * as Y from 'yjs';
import * as encoding from 'lib0/encoding';
import * as decoding from 'lib0/decoding';
import * as syncProtocol from 'y-protocols/sync';
import * as awarenessProtocol from 'y-protocols/awareness';
import { getCollaborativeTitle, projectMarkdownDraftToMarkdown, projectRichDraftToMarkdown, seedMarkdownDraft, seedRichDraftFromMarkdown } from '../shared/collaboration-schema.js';
import type { Draft, DraftMode, Proposal } from '../shared/types.js';
import { getDocumentAccess } from './acl.js';
import { requireUserId } from './auth.js';
import type { AppContext } from './context.js';
import { transaction } from './db.js';
import { badRequest, conflict, forbidden, notFound, reviewRequired } from './errors.js';
import { isoNow } from './security.js';
import { validateBody, validateParams } from './validation.js';
import { z } from 'zod';

const Id=z.string().uuid();
const Params=z.object({id:Id}).strict();
const DraftParams=z.object({draftId:Id}).strict();
const CreateBody=z.object({mode:z.enum(['markdown','rich'])}).strict();
const SubmitBody=z.object({expectedSeq:z.number().int().nonnegative(),expectedBaseVersion:z.number().int().positive(),expectedTitle:z.string().max(200),expectedBody:z.string().max(512000)}).strict();
const Title=z.string().max(200).refine(v=>Array.from(v).length<=200&&!/[\u0000-\u001f\u007f]/.test(v));
const MAX_BODY_BYTES=512000;
const MAX_STATE_BYTES=1024*1024;
const MAX_FRAME_BYTES=128*1024;
const MAX_ROOM_CONNECTIONS=20;
const MAX_GLOBAL_CONNECTIONS=300;
const MAX_MESSAGES_PER_MINUTE=300;
const CLOSED_AUTH=4401;
const CLOSED_ACCESS=4403;
const CLOSED_LIMIT=4409;
const CLOSED_INVALID=4400;

type DraftRow={id:string;doc_id:string;mode:DraftMode;base_version:number;state:Draft['state'];y_state:Uint8Array;seq:number;title:string;updated_by:string;updated_at:string;space_id:string;team_id:string;doc_version:number;document_title:string;document_body:string};
type Peer={socket:WebSocket;request:FastifyRequest;userId:string;name:string;role:string;color:string;clientIds:Set<number>;openedAt:number;windowStarted:number;messageCount:number;tail:Promise<void>};
type Room={id:string;doc:Y.Doc;awareness:awarenessProtocol.Awareness;awarenessHandler:(...args:any[])=>void;peers:Set<Peer>;clientOwners:Map<number,Peer>;seq:number;state:'editing'|'reviewing';writeChain:Promise<void>};

function colorFor(userId:string):string{const colors=['#4477aa','#bb5566','#228833','#aa3377','#66ccee','#ccbb44','#ee6677','#4477aa'];let hash=0;for(const c of userId)hash=(hash*31+c.charCodeAt(0))|0;return colors[Math.abs(hash)%colors.length];}
function dto(row:Pick<DraftRow,'id'|'doc_id'|'mode'|'base_version'|'state'|'seq'>):Draft{return{id:row.id,documentId:row.doc_id,mode:row.mode,baseVersion:row.base_version,state:row.state,seq:row.seq};}
function loadDraft(db:AppContext['db'],draftId:string):DraftRow|undefined{return db.prepare(`SELECT dr.id,dr.doc_id,dr.mode,dr.base_version,dr.state,dr.y_state,dr.seq,dr.title,dr.updated_by,dr.updated_at,d.space_id,s.team_id,d.version AS doc_version,d.title AS document_title,d.body AS document_body
 FROM document_drafts dr JOIN documents d ON d.id=dr.doc_id JOIN spaces s ON s.id=d.space_id WHERE dr.id=?`).get(draftId) as DraftRow|undefined;}
function project(doc:Y.Doc,mode:DraftMode):{title:string;body:string}{const title=getCollaborativeTitle(doc)?.toString()??'';if(!Title.safeParse(title).success)throw badRequest('草稿标题格式无效。');const result=mode==='markdown'?projectMarkdownDraftToMarkdown(doc.getText('body')):projectRichDraftToMarkdown(doc.getXmlFragment('body'));if(!result.ok)throw badRequest('富文本草稿包含不支持或无法安全转换的内容。');if(Buffer.byteLength(result.value,'utf8')>MAX_BODY_BYTES)throw badRequest('草稿正文超过500KB。');return{title:title.trim(),body:result.value};}
function makeDoc(row:DraftRow):Y.Doc{const doc=new Y.Doc();Y.applyUpdate(doc,Uint8Array.from(row.y_state));return doc;}
function audit(db:AppContext['db'],teamId:string,userId:string,action:string,targetId:string,details:Record<string,unknown>):void{db.prepare(`INSERT INTO audit_events(id,team_id,actor_id,action,target_type,target_id,created_at,details_json) VALUES(?,?,?,'draft.'||?,'document',?,?,?)`).run(randomUUID(),teamId,userId,action,targetId,isoNow(),JSON.stringify(details));}
function requireEditor(db:AppContext['db'],userId:string,documentId:string){const access=getDocumentAccess(db,userId,documentId);if(!access?.canRead)throw notFound();if(!access.canEdit)throw forbidden();return access;}
function asProposal(db:AppContext['db'],id:string){const row=db.prepare(`SELECT p.*,u.name AS author_name FROM proposals p JOIN users u ON u.id=p.author_id WHERE p.id=?`).get(id) as Record<string,unknown>|undefined;if(!row)throw notFound();return {proposal:{id:row.id,teamId:row.team_id,spaceId:row.space_id,documentId:row.target_document_id??row.document_id,kind:row.kind,authorId:row.author_id,authorName:row.author_name,baseVersion:row.base_version,title:row.title,status:row.status,reviewerId:row.reviewer_id,decisionNote:row.decision_note,createdAt:row.created_at,decidedAt:row.decided_at,body:row.body,sourceDraftId:row.source_draft_id,revisionId:row.revision_id}};}
function authorizePeer(db:AppContext['db'],peer:Peer,draftId:string):DraftRow|undefined{try{if(requireUserId(db,peer.request)!==peer.userId)return undefined;const row=loadDraft(db,draftId);if(!row||row.state!=='editing')return undefined;const access=getDocumentAccess(db,peer.userId,row.doc_id);if(!access?.canEdit)return undefined;const member=db.prepare('SELECT m.role,u.name FROM members m JOIN users u ON u.id=m.user_id WHERE m.team_id=? AND m.user_id=?').get(row.team_id,peer.userId) as {role:string;name:string}|undefined;if(!member)return undefined;peer.role=member.role;peer.name=member.name;return row;}catch{return undefined;}}
function sendSyncStep1(socket:WebSocket,doc:Y.Doc):void{const encoder=encoding.createEncoder();encoding.writeVarUint(encoder,0);syncProtocol.writeSyncStep2(encoder,doc);socket.send(encoding.toUint8Array(encoder));const second=encoding.createEncoder();encoding.writeVarUint(second,0);syncProtocol.writeSyncStep1(second,doc);socket.send(encoding.toUint8Array(second));}
function parseAwarenessIds(data:Uint8Array):Array<{id:number;clock:number;state:unknown}>{const decoder=decoding.createDecoder(data);const count=decoding.readVarUint(decoder);if(count>32)throw new Error('too many awareness states');const result:Array<{id:number;clock:number;state:unknown}>=[];for(let i=0;i<count;i++){const id=decoding.readVarUint(decoder);const clock=decoding.readVarUint(decoder);const state=JSON.parse(decoding.readVarString(decoder)) as unknown;if(state!==null&&(typeof state!=='object'||Array.isArray(state)))throw new Error('invalid awareness state');result.push({id,clock,state});}if(decoding.hasContent(decoder))throw new Error('trailing awareness bytes');return result;}
function safeCursor(value:unknown):unknown{if(!value||typeof value!=='object')return undefined;const text=JSON.stringify(value);if(text.length>4096)return undefined;return value;}

export function registerCollaborationRoutes(app:FastifyInstance,{db,config}:AppContext):void{
 const rooms=new Map<string,Room>();const allPeers=new Set<Peer>();let heartbeat:NodeJS.Timeout|undefined;
 const closeRoom=(room:Room)=>{room.awareness.off('update',room.awarenessHandler as never);room.awareness.destroy();room.doc.destroy();};
 const closePeer=(room:Room,peer:Peer,code:number,reason:string)=>{if(!room.peers.delete(peer))return;allPeers.delete(peer);for(const clientId of peer.clientIds){room.clientOwners.delete(clientId);awarenessProtocol.removeAwarenessStates(room.awareness,[clientId],peer);}if(peer.socket.readyState===1)peer.socket.close(code,reason);if(room.peers.size===0&&rooms.get(room.id)===room){rooms.delete(room.id);closeRoom(room);}};
 const refreshAwareness=(room:Room,peer:Peer)=>{for(const clientId of peer.clientIds){const state=room.awareness.states.get(clientId);const meta=room.awareness.meta.get(clientId);if(!state||!meta)continue;const next={...state,user:{userId:peer.userId,name:peer.name,role:peer.role,color:peer.color}};const encoder=encoding.createEncoder();encoding.writeVarUint(encoder,1);encoding.writeVarUint(encoder,1);encoding.writeVarUint(encoder,clientId);encoding.writeVarUint(encoder,meta.clock+1);encoding.writeVarString(encoder,JSON.stringify(next));awarenessProtocol.applyAwarenessUpdate(room.awareness,encoding.toUint8Array(encoder),peer);}};
 const reauthorize=(room:Room,peer:Peer,draftId:string)=>{const oldRole=peer.role;const oldName=peer.name;const row=authorizePeer(db,peer,draftId);if(row&&(oldRole!==peer.role||oldName!==peer.name))refreshAwareness(room,peer);return row;};
 const getRoom=(row:DraftRow):Room=>{const existing=rooms.get(row.id);if(existing)return existing;const doc=makeDoc(row);const awareness=new awarenessProtocol.Awareness(doc);awareness.setLocalState(null);const room:Room={id:row.id,doc,awareness,peers:new Set(),clientOwners:new Map(),seq:row.seq,state:row.state,writeChain:Promise.resolve(),awarenessHandler:undefined as never};const handler=({added,updated,removed}: {added:number[];updated:number[];removed:number[]},origin:unknown)=>{const changed=[...added,...updated,...removed];if(!changed.length)return;const data=awarenessProtocol.encodeAwarenessUpdate(awareness,changed);const encoder=encoding.createEncoder();encoding.writeVarUint(encoder,1);encoding.writeVarUint8Array(encoder,data);const payload=encoding.toUint8Array(encoder);for(const peer of room.peers){if(peer.socket.readyState===1&&peer.socket!==origin)peer.socket.send(payload);}};room.awarenessHandler=handler;awareness.on('update',handler);rooms.set(row.id,room);return room;};
 const shutdown=()=>{if(heartbeat)clearInterval(heartbeat);for(const peer of [...allPeers]){const room=[...rooms.values()].find(item=>item.peers.has(peer));if(room)closePeer(room,peer,1001,'server closing');}for(const room of rooms.values())closeRoom(room);rooms.clear();};
 app.addHook('onClose',async()=>shutdown());
 heartbeat=setInterval(()=>{for(const room of rooms.values())for(const peer of [...room.peers])if(!reauthorize(room,peer,room.id))closePeer(room,peer,CLOSED_ACCESS,'access changed');},15000);heartbeat.unref();
 app.post('/documents/:id/draft',{preValidation:[validateParams(Params),validateBody(CreateBody)]},async(request,reply)=>{
  if(request.agentPrincipal)throw forbidden('协作草稿仅支持浏览器会话。');const userId=requireUserId(db,request);const {id}=request.params as z.infer<typeof Params>;const input=request.body as z.infer<typeof CreateBody>;const access=requireEditor(db,userId,id);
  const current=db.prepare('SELECT id,title,body FROM documents WHERE id=?').get(id) as {id:string;title:string;body:string}|undefined;if(!current)throw notFound();
  const active=db.prepare("SELECT id FROM document_drafts WHERE doc_id=? AND state='editing'").get(id) as {id:string}|undefined;if(active)throw conflict('已有协作草稿，请继续编辑。');
  let doc:Y.Doc;if(input.mode==='markdown'){doc=new Y.Doc();const seeded=seedMarkdownDraft(doc,current.body,current.title);if(!seeded.ok)throw badRequest('无法初始化 Markdown 协作草稿。');}else{const seeded=seedRichDraftFromMarkdown(current.body,current.title);if(!seeded.ok)throw badRequest('文档无法无损转换为富文本；请使用 Markdown 模式。');doc=seeded.value.document;}
  project(doc,input.mode);const draftId=randomUUID(),now=isoNow();transaction(db,()=>{db.prepare(`INSERT INTO document_drafts(id,doc_id,mode,base_version,state,y_state,seq,title,updated_by,updated_at) VALUES(?,?,?,?,'editing',?,0,?,?,?)`).run(draftId,id,input.mode,access.version,Buffer.from(Y.encodeStateAsUpdate(doc)),current.title,userId,now);audit(db,access.teamId,userId,'create',draftId,{mode:input.mode,documentId:id});});doc.destroy();const row=loadDraft(db,draftId)!;return reply.code(201).send({draft:dto(row)});
 });
 app.get('/documents/:id/draft',{preValidation:validateParams(Params)},async(request)=>{if(request.agentPrincipal)throw forbidden('协作草稿仅支持浏览器会话。');const userId=requireUserId(db,request);const {id}=request.params as z.infer<typeof Params>;requireEditor(db,userId,id);const row=db.prepare("SELECT id,doc_id,mode,base_version,state,seq FROM document_drafts WHERE doc_id=? AND state='editing'").get(id) as Pick<DraftRow,'id'|'doc_id'|'mode'|'base_version'|'state'|'seq'>|undefined;if(!row)throw notFound();return{draft:dto(row)};});
 const finish=async(request:FastifyRequest,publish:boolean)=>{if(request.agentPrincipal)throw forbidden('协作草稿仅支持浏览器会话。');const userId=requireUserId(db,request);const {id}=request.params as z.infer<typeof Params>;const expected=request.body as z.infer<typeof SubmitBody>;const row=db.prepare(`SELECT dr.id,dr.doc_id,dr.mode,dr.base_version,dr.state,dr.y_state,dr.seq,dr.title,dr.updated_by,dr.updated_at,d.space_id,s.team_id,d.version AS doc_version,d.title AS document_title,d.body AS document_body FROM document_drafts dr JOIN documents d ON d.id=dr.doc_id JOIN spaces s ON s.id=d.space_id WHERE dr.doc_id=? AND dr.state='editing'`).get(id) as DraftRow|undefined;if(!row)throw notFound();const access=requireEditor(db,userId,id);if(row.doc_version!==row.base_version||expected.expectedBaseVersion!==row.base_version||expected.expectedSeq!==row.seq)throw conflict('草稿或正式文档版本已变化，请同步后重试。');const doc=makeDoc(row);const projected=project(doc,row.mode);doc.destroy();if(projected.title!==expected.expectedTitle||projected.body!==expected.expectedBody)throw conflict('草稿尚未同步完成，请等待协作状态同步后重试。');const review=db.prepare('SELECT require_review FROM spaces WHERE id=?').get(row.space_id) as {require_review:number};if(publish&&review.require_review)throw reviewRequired();if(!publish&&!review.require_review)throw conflict('此空间未启用审批流程。');const now=isoNow();let proposalId='';let version=row.doc_version;
  transaction(db,()=>{const fresh=loadDraft(db,row.id);const freshAccess=getDocumentAccess(db,userId,id);if(!fresh||fresh.state!=='editing'||!freshAccess?.canEdit)throw conflict('草稿权限或状态已变化。');if(fresh.seq!==expected.expectedSeq||fresh.base_version!==expected.expectedBaseVersion||fresh.doc_version!==fresh.base_version)throw conflict('草稿或正式文档版本已变化，请同步后重试。');const freshDoc=makeDoc(fresh);const freshProjected=project(freshDoc,fresh.mode);freshDoc.destroy();if(freshProjected.title!==expected.expectedTitle||freshProjected.body!==expected.expectedBody)throw conflict('草稿尚未同步完成，请等待协作状态同步后重试。');if(!publish){proposalId=randomUUID();db.prepare(`INSERT INTO proposals(id,team_id,space_id,document_id,target_document_id,kind,author_id,base_version,title,body,source_draft_id,status,created_at) VALUES(?,?,?,?,?,'update',?,?,?,?,?,'pending',?)`).run(proposalId,row.team_id,row.space_id,id,id,userId,row.base_version,freshProjected.title,freshProjected.body,row.id,now);audit(db,row.team_id,userId,'submit',proposalId,{kind:'update',sourceDraftId:row.id});}else{version=row.doc_version+1;const update=db.prepare('UPDATE documents SET title=?,body=?,version=?,updated_by=?,updated_at=? WHERE id=? AND version=?').run(freshProjected.title,freshProjected.body,version,userId,now,id,row.base_version);if(update.changes!==1)throw conflict();const user=db.prepare('SELECT name FROM users WHERE id=?').get(userId) as {name:string};db.prepare('INSERT INTO revisions(id,document_id,version,title,body,created_at,created_by,author_name) VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),id,version,freshProjected.title,freshProjected.body,now,userId,user.name);audit(db,row.team_id,userId,'publish',id,{version,sourceDraftId:row.id});}db.prepare("UPDATE document_drafts SET state='reviewing',updated_by=?,updated_at=? WHERE id=? AND state='editing'").run(userId,now,row.id);});
  const locked=loadDraft(db,row.id);if(locked)for(const peer of [...(rooms.get(row.id)?.peers??[])]){const room=rooms.get(row.id);if(room)closePeer(room,peer,CLOSED_ACCESS,'draft frozen');}return publish?{published:true,version,documentId:id}:{proposal:asProposal(db,proposalId).proposal};};
 app.post('/documents/:id/draft/submit',{preValidation:[validateParams(Params),validateBody(SubmitBody)]},async(request)=>finish(request,false));
 app.post('/documents/:id/draft/publish',{preValidation:[validateParams(Params),validateBody(SubmitBody)]},async(request)=>finish(request,true));
 app.get('/collaboration/:draftId',{websocket:true,preValidation:validateParams(DraftParams)},(socket,request)=>{
  if(request.headers.origin!==config.appOrigin)return socket.close(CLOSED_AUTH,'origin rejected');
  const reject=(code:number,reason:string)=>{if(socket.readyState===1)socket.close(code,reason);else socket.terminate();};
  let userId:string;try{if(request.headers.authorization||!request.headers.cookie)throw new Error('auth');userId=requireUserId(db,request);}catch{return reject(CLOSED_AUTH,'session required');}
  const {draftId}=request.params as z.infer<typeof DraftParams>;const row=loadDraft(db,draftId);if(!row||row.state!=='editing')return reject(CLOSED_ACCESS,'draft unavailable');const access=getDocumentAccess(db,userId,row.doc_id);if(!access?.canEdit)return reject(CLOSED_ACCESS,'access denied');if(allPeers.size>=MAX_GLOBAL_CONNECTIONS)return reject(CLOSED_LIMIT,'connection limit');
  const user=db.prepare('SELECT name FROM users WHERE id=?').get(userId) as {name:string};const room=getRoom(row);if(room.peers.size>=MAX_ROOM_CONNECTIONS)return reject(CLOSED_LIMIT,'room full');const peer:Peer={socket,request,userId,name:user.name,role:access.teamRole,color:colorFor(userId),clientIds:new Set(),openedAt:Date.now(),windowStarted:Date.now(),messageCount:0,tail:Promise.resolve()};room.peers.add(peer);allPeers.add(peer);
  socket.on('message',(raw,isBinary)=>{if(!isBinary)return reject(CLOSED_INVALID,'binary frames required');const data=new Uint8Array(raw as Buffer);if(data.byteLength>MAX_FRAME_BYTES)return reject(CLOSED_LIMIT,'frame too large');const now=Date.now();if(now-peer.windowStarted>60000){peer.windowStarted=now;peer.messageCount=0;}if(++peer.messageCount>MAX_MESSAGES_PER_MINUTE)return reject(CLOSED_LIMIT,'rate limit');if(!reauthorize(room,peer,draftId))return closePeer(room,peer,CLOSED_ACCESS,'access changed');let failureReason='invalid collaboration message';peer.tail=peer.tail.then(async()=>{
    const decoder=decoding.createDecoder(data);const messageType=decoding.readVarUint(decoder);
    if(messageType===0){failureReason='invalid sync message';const subtype=decoding.readVarUint(decoder);if(subtype===0){const stateVector=decoding.readVarUint8Array(decoder);const encoder=encoding.createEncoder();encoding.writeVarUint(encoder,0);syncProtocol.writeSyncStep2(encoder,room.doc,stateVector);socket.send(encoding.toUint8Array(encoder));const step1=encoding.createEncoder();encoding.writeVarUint(step1,0);syncProtocol.writeSyncStep1(step1,room.doc);socket.send(encoding.toUint8Array(step1));return;}if(subtype!==1&&subtype!==2)throw new Error('invalid sync subtype');const update=decoding.readVarUint8Array(decoder);if(decoding.hasContent(decoder))throw new Error('trailing sync bytes');const operation=room.writeChain.then(()=>{const candidate=new Y.Doc();try{Y.applyUpdate(candidate,Y.encodeStateAsUpdate(room.doc));Y.applyUpdate(candidate,update);const projected=project(candidate,row.mode);const nextSeq=room.seq+1;const snapshot=Buffer.from(Y.encodeStateAsUpdate(candidate));if(snapshot.length>MAX_STATE_BYTES)throw new Error('draft state too large');transaction(db,()=>{const current=loadDraft(db,draftId);if(!current||current.state!=='editing'||current.seq!==room.seq||current.base_version!==current.doc_version)throw new Error('draft changed');const result=db.prepare("UPDATE document_drafts SET y_state=?,seq=?,title=?,updated_by=?,updated_at=? WHERE id=? AND state='editing' AND seq=?").run(snapshot,nextSeq,projected.title,peer.userId,isoNow(),draftId,room.seq);if(result.changes!==1)throw new Error('draft CAS failed');db.prepare('INSERT INTO draft_updates(draft_id,seq,update_blob,user_id,created_at) VALUES(?,?,?,?,?)').run(draftId,nextSeq,Buffer.from(update),peer.userId,isoNow());db.prepare('DELETE FROM draft_updates WHERE draft_id=? AND seq<=?').run(draftId,nextSeq-2000);});Y.applyUpdate(room.doc,update);room.seq=nextSeq;const out=encoding.createEncoder();encoding.writeVarUint(out,0);syncProtocol.writeUpdate(out,update);const frame=encoding.toUint8Array(out);for(const other of [...room.peers]){if(!reauthorize(room,other,draftId)){closePeer(room,other,CLOSED_ACCESS,'access changed');continue;}if(other.socket.readyState===1)other.socket.send(frame);}}finally{candidate.destroy();}});room.writeChain=operation.then(()=>undefined,()=>undefined);await operation;return;}
    if(messageType===1){failureReason='invalid awareness update';const update=decoding.readVarUint8Array(decoder);if(decoding.hasContent(decoder))throw new Error('trailing awareness bytes');const parsed=parseAwarenessIds(update);const accepted:Array<{id:number;clock:number;state:unknown}>=[];for(const item of parsed){const owner=room.clientOwners.get(item.id);if(owner&&owner!==peer)continue;if(item.state===null){if(owner===peer){room.clientOwners.delete(item.id);peer.clientIds.delete(item.id);accepted.push(item);}else{continue;}}else{room.clientOwners.set(item.id,peer);peer.clientIds.add(item.id);accepted.push(item);}}
     const filteredEncoder=encoding.createEncoder();encoding.writeVarUint(filteredEncoder,accepted.length);for(const item of accepted){encoding.writeVarUint(filteredEncoder,item.id);encoding.writeVarUint(filteredEncoder,item.clock);encoding.writeVarString(filteredEncoder,JSON.stringify(item.state));}const filtered=encoding.toUint8Array(filteredEncoder);if(!accepted.length)return;const safe=awarenessProtocol.modifyAwarenessUpdate(filtered,state=>{if(state===null)return null;const value=state as Record<string,unknown>;const cursor=safeCursor(value.cursor);return {user:{userId:peer.userId,name:peer.name,role:peer.role,color:peer.color},...(cursor===undefined?{}:{cursor})};});awarenessProtocol.applyAwarenessUpdate(room.awareness,safe,peer);return;}
    if(messageType===3){const out=encoding.createEncoder();encoding.writeVarUint(out,1);encoding.writeVarUint8Array(out,awarenessProtocol.encodeAwarenessUpdate(room.awareness,[...room.awareness.states.keys()]));socket.send(encoding.toUint8Array(out));return;}
    throw new Error('unsupported message');
   }).catch((error:unknown)=>{if(process.env.TEAMSHELF_DEBUG_COLLAB==='1'&&error instanceof Error)console.error('collaboration-frame-error',JSON.stringify({name:error.name,message:error.message,stack:error.stack}));closePeer(room,peer,CLOSED_INVALID,failureReason);});});
  socket.on('close',()=>closePeer(room,peer,1000,'closed'));socket.on('error',()=>closePeer(room,peer,CLOSED_INVALID,'socket error'));
 });
}
