import { createHash, randomUUID } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { ExternalRoomSummary } from '../shared/types.js';
import { getDocumentAccess } from './acl.js';
import { requireUserId } from './auth.js';
import type { AppContext } from './context.js';
import { transaction } from './db.js';
import { badRequest, forbidden, notFound } from './errors.js';
import { hashPassword, hashToken, isoNow, newToken, verifyPassword } from './security.js';
import { validateBody, validateParams } from './validation.js';

const Id=z.string().uuid();
const TeamParams=z.object({teamId:Id}).strict();
const RoomParams=z.object({roomId:Id}).strict();
const ShareParams=z.object({token:z.string().regex(/^[A-Za-z0-9_-]{40,60}$/)}).strict();
const DocParams=z.object({roomId:Id,documentId:Id}).strict();
const CreateBody=z.object({name:z.string().trim().min(1).max(80),expiresAt:z.string().datetime({offset:true}),password:z.string().min(12).max(128),items:z.array(z.object({documentId:Id,publishedVersion:z.number().int().positive()}).strict()).min(1).max(100)}).strict();
const RotateBody=z.object({password:z.string().min(12).max(128).optional()}).strict();
const PasswordBody=z.object({password:z.string().min(1).max(128)}).strict();
const RefreshBody=z.object({publishedVersion:z.number().int().positive()}).strict();
const PageQuery=z.object({offset:z.coerce.number().int().nonnegative().default(0),limit:z.coerce.number().int().min(1).max(100).default(50)}).strict();
const SessionCookie='teamshelf_share';
function validateQuery(schema:z.ZodTypeAny){return async(request:FastifyRequest)=>{const parsed=schema.safeParse(request.query);if(!parsed.success)throw badRequest('查询参数格式无效。');(request as FastifyRequest & {query:unknown}).query=parsed.data;};}

type RoomRow={id:string;team_id:string;created_by:string|null;name:string;token_hash:string;password_hash:string;session_generation:number;expires_at:string;revoked_at:string|null;created_at:string;rotated_at:string|null};
type Snapshot={document_id:string;version:number;title:string;body:string;space_id:string;team_id:string};
function sessionUser(db:AppContext['db'],request:FastifyRequest):string{if(request.agentPrincipal)throw forbidden('外部资料室管理仅支持浏览器会话。');return requireUserId(db,request);}
function audit(db:AppContext['db'],teamId:string,userId:string,action:string,targetId:string,details:unknown):void{db.prepare(`INSERT INTO audit_events(id,team_id,actor_id,action,target_type,target_id,created_at,details_json) VALUES(?,?,?,?,?,?,?,?)`).run(randomUUID(),teamId,userId,action,'external_room',targetId,isoNow(),JSON.stringify(details));}
function requireManager(db:AppContext['db'],teamId:string,userId:string):void{const row=db.prepare('SELECT role FROM members WHERE team_id=? AND user_id=?').get(teamId,userId) as {role:string}|undefined;if(!row)throw notFound();if(row.role!=='owner'&&row.role!=='admin')throw forbidden();}
function summary(db:AppContext['db'],row:RoomRow):ExternalRoomSummary{const count=(db.prepare('SELECT COUNT(*) AS count FROM external_room_items WHERE room_id=?').get(row.id) as {count:number}).count;const last=db.prepare('SELECT MAX(accessed_at) AS accessed_at FROM external_room_access_logs WHERE room_id=?').get(row.id) as {accessed_at:string|null};return{id:row.id,teamId:row.team_id,name:row.name,expiresAt:row.expires_at,revokedAt:row.revoked_at,itemCount:Number(count),createdAt:row.created_at,createdBy:row.created_by??'',lastAccessAt:last.accessed_at};}
function managerRooms(db:AppContext['db'],teamId:string):RoomRow[]{return db.prepare('SELECT * FROM external_rooms WHERE team_id=? ORDER BY created_at DESC,id').all(teamId) as RoomRow[];}
function snapshot(db:AppContext['db'],userId:string,teamId:string,documentId:string,version:number):Snapshot{const access=getDocumentAccess(db,userId,documentId);if(!access?.canManage||access.teamId!==teamId)throw notFound();const row=db.prepare(`SELECT r.document_id,r.version,r.title,r.body,d.space_id,s.team_id FROM revisions r JOIN documents d ON d.id=r.document_id JOIN spaces s ON s.id=d.space_id WHERE r.document_id=? AND r.version=?`).get(documentId,version) as Snapshot|undefined;if(!row||row.team_id!==teamId)throw notFound();return row;}
function aclFingerprint(db:AppContext['db'],documentId:string):string{const row=db.prepare(`SELECT d.visibility AS doc_visibility,s.visibility AS space_visibility,d.space_id,s.team_id FROM documents d JOIN spaces s ON s.id=d.space_id WHERE d.id=?`).get(documentId) as {doc_visibility:string;space_visibility:string;space_id:string;team_id:string}|undefined;if(!row)throw notFound();const spaces=db.prepare('SELECT user_id,role FROM space_grants WHERE space_id=? ORDER BY user_id,role').all(row.space_id);const docs=db.prepare('SELECT user_id,role FROM document_grants WHERE document_id=? ORDER BY user_id,role').all(documentId);const members=db.prepare('SELECT user_id,role FROM members WHERE team_id=? ORDER BY user_id,role').all(row.team_id);return createHash('sha256').update(JSON.stringify([row,spaces,docs,members])).digest('hex');}
function logAccess(db:AppContext['db'],roomId:string,outcome:'session_created'|'items_viewed'|'document_viewed',documentId:string|null=null):void{db.prepare('INSERT INTO external_room_access_logs(id,room_id,document_id,outcome,accessed_at) VALUES(?,?,?,?,?)').run(randomUUID(),roomId,documentId,outcome,isoNow());}
function activeRoom(db:AppContext['db'],roomId:string):RoomRow{const row=db.prepare('SELECT * FROM external_rooms WHERE id=?').get(roomId) as RoomRow|undefined;if(!row||row.revoked_at||row.expires_at<=isoNow())throw notFound();if(!row.created_by)throw notFound();const role=db.prepare('SELECT role FROM members WHERE team_id=? AND user_id=?').get(row.team_id,row.created_by) as {role:string}|undefined;if(!role||!['owner','admin'].includes(role.role))throw notFound();return row;}
function publicRoom(db:AppContext['db'],request:FastifyRequest,token:string):{room:RoomRow;sessionHash:string}{const room=db.prepare('SELECT * FROM external_rooms WHERE token_hash=?').get(hashToken(token)) as RoomRow|undefined;if(!room)throw notFound();const current=activeRoom(db,room.id);const raw=request.cookies?.[SessionCookie];if(!raw)throw forbidden('请先输入资料室口令。');const sessionHash=hashToken(raw);const valid=db.prepare(`SELECT 1 FROM external_room_sessions WHERE token_hash=? AND room_id=? AND session_generation=? AND expires_at>?`).get(sessionHash,current.id,current.session_generation,isoNow());if(!valid)throw forbidden('资料室会话已失效，请重新输入口令。');return{room:current,sessionHash};}
function publicDocuments(db:AppContext['db'],room:RoomRow):Array<{documentId:string;title:string;body:string;version:number}>{const items=db.prepare(`SELECT i.document_id,i.published_version,i.title_snapshot,i.body_snapshot,i.acl_fingerprint,d.id AS live_document FROM external_room_items i LEFT JOIN documents d ON d.id=i.document_id WHERE i.room_id=? ORDER BY i.created_at,i.document_id`).all(room.id) as Array<{document_id:string;published_version:number;title_snapshot:string;body_snapshot:string;acl_fingerprint:string;live_document:string|null}>;const results=[] as Array<{documentId:string;title:string;body:string;version:number}>;for(const item of items){if(!item.live_document)continue;let fingerprint:string;try{fingerprint=aclFingerprint(db,item.document_id);}catch{continue;}if(fingerprint!==item.acl_fingerprint)continue;results.push({documentId:item.document_id,title:item.title_snapshot,body:item.body_snapshot,version:item.published_version});}return results;}
function cookieExpiry(room:RoomRow):number{return Math.max(0,Math.floor((Date.parse(room.expires_at)-Date.now())/1000));}
function setNoReferrer(reply:FastifyReply):void{reply.header('referrer-policy','no-referrer').header('cache-control','no-store');}
function requireSameOrigin(request:FastifyRequest,config:AppContext['config']):void{if(request.headers.origin!==undefined&&request.headers.origin!==config.appOrigin)throw forbidden('请求来源不允许。');}
function roomUrl(config:AppContext['config'],token:string):string{return`${config.appOrigin}/share/${token}`;}

export function registerExternalRoomRoutes(app:FastifyInstance,context:AppContext):void{
 const {db,config}=context;
 app.post('/teams/:teamId/rooms',{preValidation:[validateParams(TeamParams),validateBody(CreateBody)]},async(request,reply)=>{const user=sessionUser(db,request);const {teamId}=request.params as z.infer<typeof TeamParams>;requireManager(db,teamId,user);const input=request.body as z.infer<typeof CreateBody>;const now=Date.now(),expiry=Date.parse(input.expiresAt);if(!Number.isFinite(expiry)||expiry<=now||expiry>now+90*86400000)throw forbidden('资料室有效期须为未来90天内。');if(new Set(input.items.map(x=>x.documentId)).size!==input.items.length)throw forbidden('资料室不能重复包含同一文档。');const chosen=input.items.map(item=>({...item,revision:snapshot(db,user,teamId,item.documentId,item.publishedVersion),fingerprint:aclFingerprint(db,item.documentId)}));const roomId=randomUUID(),token=newToken(),nowIso=isoNow(),passwordHash=await hashPassword(input.password);transaction(db,()=>{db.prepare(`INSERT INTO external_rooms(id,team_id,created_by,name,token_hash,password_hash,session_generation,expires_at,created_at) VALUES(?,?,?,?,?,?,1,?,?)`).run(roomId,teamId,user,input.name,hashToken(token),passwordHash,new Date(expiry).toISOString(),nowIso);const insert=db.prepare('INSERT INTO external_room_items(room_id,document_id,published_version,title_snapshot,body_snapshot,acl_fingerprint,created_at) VALUES(?,?,?,?,?,?,?)');for(const item of chosen)insert.run(roomId,item.documentId,item.publishedVersion,item.revision.title,item.revision.body,item.fingerprint,nowIso);audit(db,teamId,user,'external_room.create',roomId,{itemCount:chosen.length,expiresAt:new Date(expiry).toISOString()});});const row=db.prepare('SELECT * FROM external_rooms WHERE id=?').get(roomId) as RoomRow;setNoReferrer(reply);return reply.code(201).send({room:summary(db,row),url:roomUrl(config,token)});});
 app.get('/teams/:teamId/rooms',{preValidation:validateParams(TeamParams)},async request=>{const user=sessionUser(db,request);const {teamId}=request.params as z.infer<typeof TeamParams>;requireManager(db,teamId,user);return{rooms:managerRooms(db,teamId).map(row=>summary(db,row))};});
 app.delete('/rooms/:roomId',{preValidation:validateParams(RoomParams)},async request=>{const user=sessionUser(db,request);const {roomId}=request.params as z.infer<typeof RoomParams>;const room=db.prepare('SELECT * FROM external_rooms WHERE id=?').get(roomId) as RoomRow|undefined;if(!room)throw notFound();requireManager(db,room.team_id,user);transaction(db,()=>{db.prepare('UPDATE external_rooms SET revoked_at=COALESCE(revoked_at,?) ,session_generation=session_generation+1 WHERE id=?').run(isoNow(),roomId);db.prepare('DELETE FROM external_room_sessions WHERE room_id=?').run(roomId);audit(db,room.team_id,user,'external_room.revoke',roomId,{});});return{ok:true};});
 app.post('/rooms/:roomId/rotate',{preValidation:[validateParams(RoomParams),validateBody(RotateBody)]},async(request,reply)=>{const user=sessionUser(db,request);const {roomId}=request.params as z.infer<typeof RoomParams>;const room=db.prepare('SELECT * FROM external_rooms WHERE id=?').get(roomId) as RoomRow|undefined;if(!room||room.revoked_at)throw notFound();requireManager(db,room.team_id,user);const body=request.body as z.infer<typeof RotateBody>;const token=newToken(),passwordHash=body.password?await hashPassword(body.password):room.password_hash;transaction(db,()=>{db.prepare('UPDATE external_rooms SET token_hash=?,password_hash=?,session_generation=session_generation+1,rotated_at=? WHERE id=? AND revoked_at IS NULL').run(hashToken(token),passwordHash,isoNow(),roomId);db.prepare('DELETE FROM external_room_sessions WHERE room_id=?').run(roomId);audit(db,room.team_id,user,'external_room.rotate',roomId,{passwordChanged:Boolean(body.password)});});const updated=db.prepare('SELECT * FROM external_rooms WHERE id=?').get(roomId) as RoomRow;setNoReferrer(reply);return{room:summary(db,updated),url:roomUrl(config,token)};});
 app.put('/rooms/:roomId/items/:documentId/refresh',{preValidation:[validateParams(DocParams),validateBody(RefreshBody)]},async request=>{const user=sessionUser(db,request);const {roomId,documentId}=request.params as z.infer<typeof DocParams>;const room=db.prepare('SELECT * FROM external_rooms WHERE id=?').get(roomId) as RoomRow|undefined;if(!room||room.revoked_at)throw notFound();requireManager(db,room.team_id,user);const input=request.body as z.infer<typeof RefreshBody>;const revision=snapshot(db,user,room.team_id,documentId,input.publishedVersion);const fingerprint=aclFingerprint(db,documentId);const result=db.prepare('UPDATE external_room_items SET published_version=?,title_snapshot=?,body_snapshot=?,acl_fingerprint=? WHERE room_id=? AND document_id=?').run(input.publishedVersion,revision.title,revision.body,fingerprint,roomId,documentId);if(!result.changes)throw notFound();audit(db,room.team_id,user,'external_room.item_refresh',roomId,{documentId,publishedVersion:input.publishedVersion});return{ok:true};});
 app.delete('/rooms/:roomId/items/:documentId',{preValidation:validateParams(DocParams)},async request=>{const user=sessionUser(db,request);const {roomId,documentId}=request.params as z.infer<typeof DocParams>;const room=db.prepare('SELECT * FROM external_rooms WHERE id=?').get(roomId) as RoomRow|undefined;if(!room)throw notFound();requireManager(db,room.team_id,user);const result=db.prepare('DELETE FROM external_room_items WHERE room_id=? AND document_id=?').run(roomId,documentId);if(!result.changes)throw notFound();db.prepare('DELETE FROM external_room_sessions WHERE room_id=?').run(roomId);db.prepare('UPDATE external_rooms SET session_generation=session_generation+1 WHERE id=?').run(roomId);audit(db,room.team_id,user,'external_room.item_remove',roomId,{documentId});return{ok:true};});
 app.get('/rooms/:roomId/access-log',{preValidation:[validateParams(RoomParams),validateQuery(PageQuery)]},async request=>{const user=sessionUser(db,request);const {roomId}=request.params as z.infer<typeof RoomParams>;const room=db.prepare('SELECT * FROM external_rooms WHERE id=?').get(roomId) as RoomRow|undefined;if(!room)throw notFound();requireManager(db,room.team_id,user);const {offset,limit}=request.query as z.infer<typeof PageQuery>;const rows=db.prepare('SELECT id,document_id,outcome,accessed_at FROM external_room_access_logs WHERE room_id=? ORDER BY accessed_at DESC,id DESC LIMIT ? OFFSET ?').all(roomId,limit+1,offset) as Array<{id:string;document_id:string|null;outcome:string;accessed_at:string}>;const hasMore=rows.length>limit;return{events:rows.slice(0,limit).map(row=>({id:row.id,documentId:row.document_id,accessedAt:row.accessed_at,outcome:row.outcome})),hasMore,nextOffset:hasMore?offset+limit:null};});
 app.post('/share/:token/session',{config:{rateLimit:{max:5,timeWindow:60_000}},preValidation:[validateParams(ShareParams),validateBody(PasswordBody)]},async(request,reply)=>{setNoReferrer(reply);requireSameOrigin(request,config);const {token}=request.params as z.infer<typeof ShareParams>;const {password}=request.body as z.infer<typeof PasswordBody>;const room=db.prepare('SELECT * FROM external_rooms WHERE token_hash=?').get(hashToken(token)) as RoomRow|undefined;if(!room)throw notFound();const live=activeRoom(db,room.id);if(!await verifyPassword(password,live.password_hash))throw forbidden('资料室口令不正确。');const raw=newToken(),expiresAt=new Date(Math.min(Date.now()+8*60*60_000,Date.parse(live.expires_at))).toISOString();db.prepare('INSERT INTO external_room_sessions(token_hash,room_id,session_generation,created_at,expires_at) VALUES(?,?,?,?,?)').run(hashToken(raw),live.id,live.session_generation,isoNow(),expiresAt);logAccess(db,live.id,'session_created');reply.setCookie(SessionCookie,raw,{path:'/api/share',httpOnly:true,sameSite:'strict',secure:config.cookieSecure,expires:new Date(expiresAt)});return{room:{id:live.id,name:live.name,expiresAt:live.expires_at}};});
 app.get('/share/:token/items',{preValidation:validateParams(ShareParams)},async(request,reply)=>{setNoReferrer(reply);const {token}=request.params as z.infer<typeof ShareParams>;const {room}=publicRoom(db,request,token);const documents=publicDocuments(db,room);logAccess(db,room.id,'items_viewed');return{documents:documents.map(({title,body})=>({title,body}))};});
 app.get('/share/:token/documents/:documentId',{preValidation:validateParams(z.object({token:ShareParams.shape.token,documentId:Id}).strict())},async(request,reply)=>{setNoReferrer(reply);const {token,documentId}=request.params as {token:string;documentId:string};const {room}=publicRoom(db,request,token);const item=db.prepare('SELECT title_snapshot,body_snapshot,published_version,acl_fingerprint FROM external_room_items WHERE room_id=? AND document_id=?').get(room.id,documentId) as {title_snapshot:string;body_snapshot:string;published_version:number;acl_fingerprint:string}|undefined;if(!item)throw notFound();if(aclFingerprint(db,documentId)!==item.acl_fingerprint)throw notFound();logAccess(db,room.id,'document_viewed',documentId);return{document:{title:item.title_snapshot,body:item.body_snapshot}};});
}
