import { expect, test, type Page } from "@playwright/test";
import { Client, StreamableHTTPClientTransport } from "@modelcontextprotocol/client";
import { inviteUrlFromMail, startLocalTlsSmtpSink, type LocalTlsSmtpSink } from "../helpers/local-smtp.mjs";
test.use({ trace: "off", screenshot: "off" });

const setupToken = "teamshelf-e2e-setup-token-2026-only-for-isolated-tests";
const adminEmail = "owner-e2e@example.test";
const adminPassword = "Teamshelf-Test-Password-2026!";
const viewerPassword = "窗边纸船绕过深蓝群岛抵达星河2047";
let activeMailSink: LocalTlsSmtpSink | undefined;
async function enterDocumentEdit(page: Page) {
  const button = page.getByRole("button", { name: "编辑文档" });
  if (await button.count()) await button.click();
}
test.afterEach(async () => { await activeMailSink?.close(); activeMailSink = undefined; });

async function waitForNewDocumentUrl(page: Page, previousId: string | null): Promise<string> {
  await expect.poll(() => new URL(page.url()).searchParams.get("doc")).not.toBe(previousId);
  const id = new URL(page.url()).searchParams.get("doc");
  expect(id).toBeTruthy();
  return id!;
}

function basicMcpTransport(baseUrl: string, email: string, password: string) {
  const authorization = `Basic ${Buffer.from(`${email}:${password}`, "utf8").toString("base64")}`;
  return new StreamableHTTPClientTransport(new URL("/mcp", baseUrl), {
    fetch: (input, init) => {
      const headers = new Headers(init?.headers);
      headers.set("Authorization", authorization);
      return fetch(input, { ...init, headers });
    },
  });
}

test("real API flow: setup, mail invites, edit, ACL, conflict recovery and deep-link refresh", async ({ page, browser }) => {
  activeMailSink = await startLocalTlsSmtpSink();
  const sink = activeMailSink;
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "建立你的知屿" })).toBeVisible();
  await page.getByLabel("初始化口令").fill(setupToken);
  await page.getByLabel("团队名称").fill("E2E 知识团队");
  await page.getByLabel("邮箱").fill(adminEmail);
  await page.getByLabel("你的姓名").fill("E2E 管理员");
  await expect(page.getByLabel("密码")).toHaveAttribute("maxlength", "256");
  await page.getByLabel("密码").fill("短密码");
  await page.getByRole("button", { name: "创建团队空间" }).click();
  await expect(page.getByRole("alert")).toContainText("新密码需要8–128个Unicode字符");
  await page.getByLabel("密码").fill(adminPassword);
  await page.getByRole("button", { name: "创建团队空间" }).click();
  await expect(page.getByRole("heading", { name: "给团队知识，一个好去处。" })).toBeVisible();

  await page.getByRole("button", { name: "邮箱与邀请" }).click();
  const mailDialog = page.getByRole("dialog");
  const smtpHost = mailDialog.getByLabel("SMTP 主机");
  await smtpHost.fill(sink.host);
  await mailDialog.getByRole("spinbutton", { name: "端口" }).fill(String(sink.port));
  await mailDialog.getByLabel("连接加密").selectOption("tls");
  await mailDialog.getByLabel("SMTP 用户名").fill(sink.username);
  await mailDialog.getByLabel("发件邮箱").fill("teamshelf-sender@example.test");
  await mailDialog.getByLabel("发件人名称").fill("TeamShelf E2E");
  const smtpPassword = mailDialog.getByLabel("SMTP 授权码");
  await smtpPassword.fill(sink.password);
  await mailDialog.getByRole("button", { name: "保存邮箱设置" }).click();
  await expect(mailDialog.getByRole("status")).toContainText("发信邮箱设置已保存");
  await expect(smtpPassword).toHaveValue("");
  const storedMailSettings = await page.evaluate(async () => (await (await fetch("/api/mail/settings")).json()));
  expect(storedMailSettings.configured).toBe(true);
  expect(storedMailSettings.settings.hasPassword).toBe(true);
  expect(storedMailSettings.settings).not.toHaveProperty("password");
  expect(JSON.stringify(storedMailSettings)).not.toContain(sink.password);
  await smtpHost.fill("changed.smtp.invalid");
  await expect(smtpPassword).toHaveAttribute("required", "");
  await expect(mailDialog.getByRole("status").filter({ hasText: "已更改，请重新输入授权码" })).toBeVisible();
  await smtpHost.fill(sink.host);
  await expect(smtpPassword).not.toHaveAttribute("required", "");
  await mailDialog.getByLabel("发件人名称").fill("TeamShelf E2E updated");
  await mailDialog.getByRole("button", { name: "保存邮箱设置" }).click();
  await expect(mailDialog.getByRole("status")).toContainText("连接参数不变时留空可保留已存授权码");

  const mailCountBeforeTest = sink.received.length;
  await mailDialog.getByRole("button", { name: "发送测试邮件" }).click();
  await expect(mailDialog.getByRole("status")).toContainText("测试邮件已发送至 " + adminEmail);
  await expect.poll(() => sink.received.length).toBe(mailCountBeforeTest + 1);
  expect(sink.received.at(-1)?.to).toContain(adminEmail);
  expect(sink.received.at(-1)?.raw).not.toContain(sink.password);
  await mailDialog.getByRole("button", { name: "关闭对话框" }).click();

  const viewerEmail = "viewer-e2e@example.test";
  await page.getByRole("button", { name: "团队成员" }).click();
  const membersDialog = page.getByRole("dialog");
  await membersDialog.getByLabel("受邀邮箱").fill(viewerEmail);
  await membersDialog.getByLabel("邀请角色").selectOption("viewer");
  const emailInviteResponsePromise = page.waitForResponse(response => response.url().includes("/invitations/email") && response.request().method() === "POST");
  await membersDialog.getByRole("button", { name: "邮件邀请" }).click();
  const emailInviteResponse = await emailInviteResponsePromise;
  const emailInvitePayload = await emailInviteResponse.json();
  expect(emailInvitePayload).not.toHaveProperty("token");
  const viewerInviteRow = page.locator(".member-row").filter({ hasText: viewerEmail });
  await expect(viewerInviteRow).toContainText("邮件已发送");
  await membersDialog.locator(".modal-body").evaluate(element => { element.scrollTop = 0; });
  await membersDialog.screenshot({ path: "docs/MCP/images/admin-members-roles.png", animations: "disabled" });
  await expect.poll(() => sink.received.filter(mail => mail.to.includes(viewerEmail)).length).toBe(1);
  const oldInviteUrl = inviteUrlFromMail(sink.received.find(mail => mail.to.includes(viewerEmail))!);
  const oldInviteToken = new URL(oldInviteUrl).searchParams.get("invite")!;
  expect(oldInviteToken).toBeTruthy();

  sink.rejectAuth = true;
  await viewerInviteRow.getByRole("button", { name: "重新发送邮件给 " + viewerEmail }).click();
  await expect(viewerInviteRow).toContainText("发送失败");
  const expiredOldInvite = await page.request.get(new URL("/api/invitations/" + encodeURIComponent(oldInviteToken), page.url()).toString());
  expect(expiredOldInvite.status()).toBe(404);

  sink.rejectAuth = false;
  await viewerInviteRow.getByRole("button", { name: "重新发送邮件给 " + viewerEmail }).click();
  await expect(viewerInviteRow).toContainText("邮件已发送");
  await expect.poll(() => sink.received.filter(mail => mail.to.includes(viewerEmail)).length).toBe(2);
  const freshInviteUrl = inviteUrlFromMail(sink.received.filter(mail => mail.to.includes(viewerEmail)).at(-1)!);
  expect(new URL(freshInviteUrl).origin).toBe(new URL(page.url()).origin);
  expect(freshInviteUrl).not.toBe(oldInviteUrl);
  const oldInviteStillExpired = await page.request.get(new URL("/api/invitations/" + encodeURIComponent(oldInviteToken), page.url()).toString());
  expect(oldInviteStillExpired.status()).toBe(404);

  const viewerContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const viewerPage = await viewerContext.newPage();
  await viewerPage.goto(freshInviteUrl);
  await expect(viewerPage.getByRole("heading", { name: "接受团队邀请" })).toBeVisible();
  await viewerPage.getByLabel("姓名（已有账号可留空）").fill("E2E 阅读者");
  await viewerPage.getByLabel("密码").fill(viewerPassword);
  await viewerPage.getByRole("button", { name: "接受邀请并加入" }).click();
  await expect(viewerPage.getByRole("heading", { name: "给团队知识，一个好去处。" })).toBeVisible();

  await membersDialog.getByRole("button", { name: "关闭对话框" }).click();
  await page.getByRole("button", { name: "新建知识库" }).click();
  const longSpaceDialog = page.getByRole("dialog");
  await longSpaceDialog.getByLabel("知识库名称").fill("文档库使用说明");
  await longSpaceDialog.getByLabel("简介").fill("长标题排版回归用知识库。");
  await longSpaceDialog.getByRole("button", { name: "创建知识库" }).click();
  const spaceTitle = page.locator(".doc-nav-title h1");
  const spaceActions = page.locator(".space-title-actions");
  await expect(spaceTitle).toHaveText("文档库使用说明");
  await expect(page.getByRole("button", { name: "折叠文档列表" })).toBeVisible();
  const assertSpaceHeadingLayout = async (width: number) => {
    const layout = await page.evaluate(() => {
      const title = document.querySelector(".doc-nav-title h1")!;
      const actions = document.querySelector(".space-title-actions")!;
      const titleBox = title.getBoundingClientRect();
      const actionsBox = actions.getBoundingClientRect();
      const docNavBox = document.querySelector(".doc-nav")!.getBoundingClientRect();
      const style = getComputedStyle(title);
      return {
        docNavLeft: docNavBox.left,
        docNavWidth: docNavBox.width,
        titleWidth: titleBox.width,
        titleHeight: titleBox.height,
        fontSize: Number.parseFloat(style.fontSize),
        titleBottom: titleBox.bottom,
        actionsTop: actionsBox.top,
        hasHorizontalOverflow: document.documentElement.scrollWidth > innerWidth,
      };
    });
    expect(layout.titleWidth).toBeGreaterThan(200);
    expect(layout.titleHeight).toBeLessThan(layout.fontSize * 2.5);
    expect(layout.titleBottom).toBeLessThanOrEqual(layout.actionsTop);
    expect(layout.hasHorizontalOverflow).toBe(false);
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    if (width <= 760) {
      expect(layout.docNavLeft).toBeGreaterThanOrEqual(0);
      expect(layout.docNavLeft + layout.docNavWidth).toBeLessThanOrEqual(width);
      expect(layout.docNavWidth).toBeGreaterThan(width - 20);
    }
  };
  await assertSpaceHeadingLayout(1440);
  await page.screenshot({ path: "test-results/screenshots/space-heading-desktop.png" });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.getByRole("button", { name: "打开团队侧栏" }).click();
  await page.locator(".space-link").filter({ hasText: "文档库使用说明" }).click();
  const closeSpaceMobileSidebar = page.getByRole("button", { name: "关闭导航" });
  if (await closeSpaceMobileSidebar.isVisible()) await closeSpaceMobileSidebar.click();
  await expect.poll(async () => {
    const box = await page.locator(".sidebar").boundingBox();
    return box ? box.x + box.width : 0;
  }).toBeLessThanOrEqual(0);
  await expect(spaceTitle).toBeVisible();
  await expect(page.locator(".doc-nav")).toBeVisible();
  await expect(spaceActions.getByRole("button", { name: "新建文档" })).toBeVisible();
  await expect(page.locator(".pane-edge-toggle")).toHaveCount(2);
  await expect(page.locator(".pane-edge-toggle").first()).toBeHidden();
  await expect(page.locator(".pane-edge-toggle").last()).toBeHidden();
  await assertSpaceHeadingLayout(375);
  await page.screenshot({ path: "test-results/screenshots/space-heading-mobile-375.png" });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("button", { name: "新建文档" }).click();
  let createDialog = page.getByRole("dialog");
  await createDialog.getByLabel("文档标题").fill("团队公开说明");
  await createDialog.getByLabel("Markdown 正文").fill("# 团队说明\n\n欢迎来到知屿。\n\n- 协作\n- 沉淀\n");
  await createDialog.getByRole("button", { name: "创建文档" }).click();
  await expect(page.getByLabel("文档标题")).toHaveValue("团队公开说明");
  await expect(page.locator(".edit-preview")).toBeVisible();
  await page.screenshot({ path: "test-results/screenshots/document-edit-preview-desktop.png" });
  await page.setViewportSize({ width: 375, height: 812 });
  const closeMobileSidebar = page.getByRole("button", { name: "关闭导航" });
  if (await closeMobileSidebar.isVisible()) await closeMobileSidebar.click();
  await expect.poll(async () => { const box = await page.locator(".sidebar").boundingBox(); return box ? box.x + box.width : 0; }).toBeLessThanOrEqual(0);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);
  for (const label of ["关闭预览", "返回查看", "段落评论", "协作草稿"]) {
    const action = page.getByRole("button", { name: label, exact: true });
    await expect(action).toBeVisible();
    await expect(action.locator("svg")).toBeVisible();
  }
  await page.getByRole("button", { name: "关闭预览" }).click();
  await expect(page.locator(".edit-preview")).toBeHidden();
  await page.getByRole("button", { name: "打开预览" }).click();
  await expect(page.locator(".edit-preview")).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);
  await page.screenshot({ path: "test-results/screenshots/document-edit-preview-mobile-375.png" });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("button", { name: "关闭预览" }).click();
  await expect(page.locator(".edit-preview")).toBeHidden();
  await expect(page.getByLabel("文档标题")).toHaveValue("团队公开说明");
  await page.getByRole("button", { name: "打开预览" }).click();
  await page.getByRole("button", { name: "返回查看" }).click();
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await enterDocumentEdit(page);
  await expect(page).toHaveURL(/doc=[0-9a-f-]+/);
  const publicDocId = new URL(page.url()).searchParams.get("doc");
  const teamId = new URL(page.url()).searchParams.get("team");
  const spaceId = new URL(page.url()).searchParams.get("space");
  expect(publicDocId).toBeTruthy(); expect(teamId).toBeTruthy(); expect(spaceId).toBeTruthy();

  const legacyTokenRequests: string[] = [];
  viewerPage.on("request", request => { if (request.url().includes("/api/agent-tokens")) legacyTokenRequests.push(request.url()); });
  await viewerPage.getByRole("button", { name: "MCP 连接" }).click();
  const viewerMcpDialog = viewerPage.getByRole("dialog", { name: "MCP 连接" });
  await expect(viewerMcpDialog).toContainText(viewerEmail);
  await expect(viewerMcpDialog).toContainText("TEAMSHELF_MCP_URL");
  await expect(viewerMcpDialog).toContainText("TEAMSHELF_MCP_EMAIL");
  await expect(viewerMcpDialog).toContainText("TEAMSHELF_MCP_PASSWORD");
  await expect(viewerMcpDialog).not.toContainText(viewerPassword);
  await viewerMcpDialog.screenshot({ path: "docs/MCP/images/member-mcp-connection.png", animations: "disabled" });
  await viewerMcpDialog.getByRole("button", { name: "关闭", exact: true }).click();
  expect(legacyTokenRequests).toEqual([]);
  const viewerMcp = new Client({ name: "teamshelf-e2e-viewer", version: "1.0.0" });
  await viewerMcp.connect(basicMcpTransport(page.url(), viewerEmail, viewerPassword));
  const viewerTeams = await viewerMcp.callTool({ name: "list_teams", arguments: {} });
  expect(JSON.stringify(viewerTeams)).toContain(teamId);
  expect(JSON.stringify(viewerTeams)).toContain(viewerEmail);
  expect(JSON.stringify(viewerTeams)).toContain("viewer");

  await page.getByRole("tab", { name: "富文本" }).click();
  const editor = page.locator(".ProseMirror");
  await expect(editor).toBeVisible();
  await editor.click(); await page.keyboard.press("End"); await page.keyboard.type(" 安全编辑");
  const boldButton = page.getByRole("button", { name: "粗体" });
  await boldButton.hover();
  await page.mouse.down();
  await expect.poll(() => editor.evaluate(element => document.activeElement === element)).toBe(true);
  await page.mouse.up();
  await page.keyboard.type("工具栏加粗");
  await page.getByRole("button", { name: "保存", exact: true }).click();
  await expect(page.getByText(/已保存版本 · v2/)).toBeVisible();
  const saved = await page.evaluate(async id => (await (await fetch(`/api/documents/${id}`, { credentials: "same-origin" })).json()).document, publicDocId);
  expect(saved.body).toContain("安全编辑");
  expect(saved.body).toContain("**工具栏加粗**");
  await page.reload();
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await expect(page.getByLabel("文档标题")).toHaveCount(0);
  await expect(page.locator(".markdown-preview")).toContainText("安全编辑");
  await page.screenshot({ path: "test-results/screenshots/document-view-desktop.png" });
  await enterDocumentEdit(page);
  const restoredPublished = await page.evaluate(async id => (await (await fetch(`/api/documents/${id}`, { credentials: "same-origin" })).json()).document, publicDocId);
  const reviewDraft = page.getByLabel("Markdown 正文");
  await reviewDraft.fill(restoredPublished.body + "\n\n未提交草稿演示");
  page.once("dialog", dialog => dialog.dismiss());
  await page.getByRole("button", { name: "返回查看" }).click();
  await expect(page.getByLabel("Markdown 正文")).toHaveValue(/未提交草稿演示/);
  page.once("dialog", dialog => dialog.accept());
  await page.getByRole("button", { name: "返回查看" }).click();
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await expect(page.locator(".markdown-preview")).not.toContainText("未提交草稿演示");
  await expect(page.getByRole("button", { name: "继续编辑草稿" })).toBeVisible();
  await page.getByRole("button", { name: "继续编辑草稿" }).click();
  await expect(page.getByLabel("Markdown 正文")).toHaveValue(/未提交草稿演示/);
  await page.getByLabel("Markdown 正文").fill(restoredPublished.body);
  await page.getByRole("button", { name: "返回查看" }).click();
  await expect(page.getByRole("button", { name: "编辑文档" })).toBeVisible();

  // Put the parent beyond the first REST page and verify the UI fetches the complete tree.
  const paginationRequests: number[] = [];
  page.on("request", request => {
    const url = new URL(request.url());
    if (request.method() === "GET" && url.pathname === `/api/spaces/${spaceId}/documents`) paginationRequests.push(Number(url.searchParams.get("offset") ?? 0));
  });
  const fillerResult = await page.evaluate(async space => {
    for (let index = 0; index < 100; index++) {
      const response = await fetch(`/api/spaces/${space}/documents`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-Requested-With": "TeamShelf" }, body: JSON.stringify({ title: `分页填充-${String(index + 1).padStart(3, "0")}`, body: "分页回归用文档" }) });
      if (response.status !== 201) return { status: response.status, index };
    }
    return { status: 201, index: 100 };
  }, spaceId);
  expect(fillerResult).toEqual({ status: 201, index: 100 });
  await page.reload();
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await expect.poll(() => page.locator(".document-link").count()).toBe(101);
  expect(paginationRequests).toContain(0);
  expect(paginationRequests).toContain(100);

  // Independent rails keep the document/editor mounted and persist across reloads.
  const teamRailToggle = page.getByRole("button", { name: "折叠团队侧栏" });
  const documentRailToggle = page.getByRole("button", { name: "折叠文档列表" });
  const finePointer = await page.evaluate(() => matchMedia("(hover: hover) and (pointer: fine)").matches);
  const handleCenterY = async (toggle: typeof teamRailToggle, pane: ReturnType<typeof page.locator>) => {
    const handleBox = await toggle.boundingBox();
    const paneBox = await pane.boundingBox();
    expect(handleBox).not.toBeNull();
    expect(paneBox).not.toBeNull();
    return (handleBox!.y + handleBox!.height / 2) - (paneBox!.y + paneBox!.height / 2);
  };
  const initialTeamCenterOffset = await handleCenterY(teamRailToggle, page.locator(".sidebar"));
  const initialDocumentCenterOffset = await handleCenterY(documentRailToggle, page.locator(".doc-nav"));
  for (const [toggle, pane] of [[teamRailToggle, page.locator(".sidebar")], [documentRailToggle, page.locator(".doc-nav")]] as const) {
    const paneBox = await pane.boundingBox();
    const handleBox = await toggle.boundingBox();
    expect(paneBox).not.toBeNull();
    expect(handleBox).not.toBeNull();
    expect(Math.abs((handleBox!.y + handleBox!.height / 2) - (paneBox!.y + paneBox!.height / 2))).toBeLessThan(2);
    expect(Math.abs((handleBox!.x + handleBox!.width) - (paneBox!.x + paneBox!.width))).toBeLessThan(2);
    if (finePointer) {
      await page.mouse.move(paneBox!.x + paneBox!.width / 2, paneBox!.y + paneBox!.height / 2);
      await expect.poll(() => toggle.evaluate(element => Number(getComputedStyle(element).opacity))).toBeLessThan(0.2);
      await toggle.hover();
      await expect.poll(() => toggle.evaluate(element => Number(getComputedStyle(element).opacity))).toBeGreaterThan(0.9);
      if (toggle === teamRailToggle) await page.screenshot({ path: "test-results/screenshots/sidebars-edge-hover-desktop.png" });
    }
  }
  await page.mouse.move(5, 5);
  await page.screenshot({ path: "test-results/screenshots/sidebars-edge-default-desktop.png" });
  await teamRailToggle.focus();
  if (finePointer) await expect.poll(() => teamRailToggle.evaluate(element => Number(getComputedStyle(element).opacity))).toBeGreaterThan(0.9);
  await page.keyboard.press("Enter");
  await expect(page.getByRole("button", { name: "展开团队侧栏" })).toHaveAttribute("aria-expanded", "false");
  expect(Math.abs(await handleCenterY(page.getByRole("button", { name: "展开团队侧栏" }), page.locator(".sidebar")) - initialTeamCenterOffset)).toBeLessThan(2);
  await expect(page.locator("#team-sidebar-content")).toBeHidden();
  await page.keyboard.press("Tab");
  expect(await page.evaluate(() => Boolean(document.activeElement?.closest("#team-sidebar-content, #document-navigation-content")))).toBe(false);
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await documentRailToggle.focus();
  await page.keyboard.press("Enter");
  await expect(page.getByRole("button", { name: "展开文档列表" })).toBeVisible();
  expect(Math.abs(await handleCenterY(page.getByRole("button", { name: "展开文档列表" }), page.locator(".doc-nav")) - initialDocumentCenterOffset)).toBeLessThan(2);
  await expect(page.locator("#document-navigation-content")).toBeHidden();
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await page.screenshot({ path: "test-results/screenshots/sidebars-collapsed-desktop.png" });
  await page.reload();
  await expect(page.getByRole("button", { name: "展开团队侧栏" })).toBeVisible();
  await expect(page.getByRole("button", { name: "展开文档列表" })).toBeVisible();
  await expect(page.locator("#team-sidebar-content")).toBeHidden();
  await expect(page.locator("#document-navigation-content")).toBeHidden();
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await page.getByRole("button", { name: "展开团队侧栏" }).click();
  await page.getByRole("button", { name: "展开文档列表" }).click();
  await expect(page.getByRole("button", { name: "折叠团队侧栏" })).toBeVisible();
  await expect(page.getByRole("button", { name: "折叠文档列表" })).toBeVisible();

  await enterDocumentEdit(page);
  const markdownField = page.getByLabel("Markdown 正文");
  await markdownField.evaluate(element => { const field = element as HTMLTextAreaElement; field.setSelectionRange(0, 5); field.dispatchEvent(new MouseEvent("mouseup", { bubbles: true })); });
  await page.getByRole("button", { name: "段落评论" }).click();
  const comments = page.getByRole("region", { name: "文档评论" });
  await expect(comments.getByText("引用选区")).toBeVisible();
  const newComment = comments.getByLabel("新建评论");
  await newComment.fill("请 @");
  const mentionChoice = comments.getByRole("option", { name: /E2E 阅读者/ });
  await mentionChoice.click();
  await newComment.pressSequentially("跟进此段说明");
  await comments.getByRole("button", { name: "发送", exact: true }).click();
  await expect(comments.getByText("跟进此段说明")).toBeVisible();
  await expect(comments.getByText("提醒：E2E 阅读者")).toBeVisible();
  const mentionNotice = await viewerPage.evaluate(async () => (await (await fetch("/api/notifications")).json()).notifications);
  expect(mentionNotice.some((item: any) => item.body.includes("跟进此段说明"))).toBe(true);
  const thread = comments.locator(".comment-thread").filter({ hasText: "跟进此段说明" });
  await thread.getByRole("button", { name: "回复" }).click();
  await comments.getByLabel(/回复 E2E 管理员/).fill("我会核对并更新。");
  await comments.getByRole("button", { name: "发送", exact: true }).last().click();
  await expect(thread.getByText("我会核对并更新。")).toBeVisible();
  await thread.getByRole("button", { name: /标记解决/ }).click();
  await expect(thread.getByText("已解决")).toBeVisible();
  await thread.getByRole("button", { name: /重新打开/ }).click();
  await expect(thread.getByText("已解决")).toHaveCount(0);

  const workflowSection = page.getByRole("region", { name: "文档计划区域" });
  await workflowSection.getByRole("button", { name: "负责人、复核与到期计划" }).click();
  await expect(workflowSection.getByLabel("文档负责人")).toBeVisible();
  const editorOption = workflowSection.getByLabel("文档负责人").locator("option").filter({ hasText: /E2E 管理员/ });
  await workflowSection.getByLabel("文档负责人").selectOption(await editorOption.evaluate(option => (option as HTMLOptionElement).value));
  await workflowSection.getByLabel("下次复核时间").fill("2027-06-01T09:00");
  await workflowSection.getByLabel("到期时间").fill("2027-07-01T17:00");
  await workflowSection.getByRole("button", { name: "保存计划" }).click();
  await expect(workflowSection.getByRole("status")).toContainText("文档计划已保存");
  await workflowSection.getByRole("button", { name: "标记已复核" }).click();
  await expect(workflowSection.getByRole("status")).toContainText("已记录复核时间");

  await page.getByRole("button", { name: "权限体检" }).click();
  const healthDialog = page.getByRole("dialog", { name: "团队权限体检" });
  await expect(healthDialog.getByText(/位成员/)).toBeVisible();
  await expect(healthDialog.getByText(/个知识库/)).toBeVisible();
  await healthDialog.getByRole("button", { name: "关闭对话框" }).click();
  // Exercise the real review gate with a second manager: the author must not approve their own proposal.
  const reviewerEmail = "reviewer-e2e@example.test";
  await page.getByRole("button", { name: "团队成员" }).click();
  const reviewerMembersDialog = page.getByRole("dialog");
  await page.getByLabel("受邀邮箱").fill(reviewerEmail);
  await page.getByLabel("邀请角色").selectOption("admin");
  const reviewerInviteResponsePromise = page.waitForResponse(response => response.url().includes("/invitations/email") && response.request().method() === "POST");
  await reviewerMembersDialog.getByRole("button", { name: "邮件邀请" }).click();
  expect((await reviewerInviteResponsePromise).status()).toBe(201);
  await expect.poll(() => sink.received.filter(mail => mail.to.includes(reviewerEmail)).length).toBe(1);
  const reviewerInviteUrl = inviteUrlFromMail(sink.received.find(mail => mail.to.includes(reviewerEmail))!);
  const reviewerContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const reviewerPage = await reviewerContext.newPage();
  await reviewerPage.goto(reviewerInviteUrl);
  await expect(reviewerPage.getByRole("heading", { name: "接受团队邀请" })).toBeVisible();
  await reviewerPage.getByLabel("姓名（已有账号可留空）").fill("E2E 审阅管理员");
  await reviewerPage.getByLabel("密码").fill("审阅者密码包含足够多Unicode字符2048");
  await reviewerPage.getByRole("button", { name: "接受邀请并加入" }).click();
  await expect(reviewerPage.getByRole("heading", { name: "给团队知识，一个好去处。" })).toBeVisible();
  await reviewerMembersDialog.getByRole("button", { name: "关闭对话框" }).click();

  await page.getByRole("button", { name: "知识库审阅规则" }).click();
  const reviewPolicyDialog = page.getByRole("dialog", { name: "变更审阅规则" });
  const reviewToggle = reviewPolicyDialog.getByLabel("所有文档变更都需其他管理员批准");
  await expect(reviewToggle).toBeEnabled();
  await reviewToggle.check();
  await reviewPolicyDialog.getByRole("button", { name: "保存规则" }).click();
  await expect(page.locator(".toast[role=status]")).toContainText("此知识库已启用提交审阅");

  const childTitle = "分页树下的子文档";
  await page.getByRole("button", { name: "返回查看" }).click();
  const viewChildAction = page.locator(".toolbar-actions").getByRole("button", { name: "在“团队公开说明”下新建子文档" });
  await expect(viewChildAction).toBeVisible();
  await viewChildAction.click();
  const viewChildDialog = page.getByRole("dialog");
  await expect(viewChildDialog.getByText("父文档：团队公开说明")).toBeVisible();
  await expect(page).toHaveURL(new RegExp(`doc=${publicDocId}`));
  await viewChildDialog.getByRole("button", { name: "关闭对话框" }).click();

  await page.getByRole("button", { name: "编辑文档" }).click();
  const childProtectionDraft = page.locator(".source-editor");
  await childProtectionDraft.fill((await childProtectionDraft.inputValue()) + "\n\n子文档弹窗保护草稿");
  const differentParent = page.locator(".document-row").filter({ hasText: "分页填充-001" });
  const differentParentAction = differentParent.getByRole("button", { name: "在“分页填充-001”下新建子文档" });
  await differentParent.scrollIntoViewIfNeeded();
  await expect(differentParentAction).toBeVisible();
  const dismissChildNavigation = page.waitForEvent("dialog").then(async dialog => {
    expect(dialog.message()).toContain("未保存的修改");
    await dialog.dismiss();
  });
  await Promise.all([dismissChildNavigation, differentParentAction.click()]);
  await expect(childProtectionDraft).toHaveValue(/子文档弹窗保护草稿/);
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const acceptChildNavigation = page.waitForEvent("dialog").then(async dialog => {
    expect(dialog.message()).toContain("未保存的修改");
    await dialog.accept();
  });
  await Promise.all([acceptChildNavigation, differentParentAction.click()]);
  const childDialog = page.getByRole("dialog");
  await expect(childDialog.getByText("父文档：分页填充-001")).toBeVisible();
  await expect(childProtectionDraft).toHaveValue(/子文档弹窗保护草稿/);
  await childDialog.getByLabel("文档标题").fill(childTitle);
  await childDialog.getByLabel("Markdown 正文").fill("这篇子文档用于验证父子关系和审阅流程。");
  await childDialog.getByRole("button", { name: "创建文档" }).click();
  await expect(page.locator(".toast[role=status]")).toContainText("子文档提案已提交");
  await expect(page.locator(".document-link").filter({ hasText: childTitle })).toHaveCount(0);
  await page.evaluate(async id => {
    const me = await (await fetch("/api/auth/me", { credentials: "same-origin" })).json();
    sessionStorage.removeItem(`teamshelf:draft:${me.user.id}:${id}`);
  }, publicDocId);
  await page.reload();
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();

  await reviewerPage.goto(`/?team=${teamId}&space=${spaceId}&doc=${publicDocId}`);
  await expect(reviewerPage.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await reviewerPage.getByRole("button", { name: "提案审阅" }).click();
  const childReviewPanel = reviewerPage.getByRole("region", { name: "提案审阅" });
  await childReviewPanel.getByRole("button", { name: new RegExp(childTitle) }).click();
  const childProposalDetail = reviewerPage.getByRole("dialog", { name: childTitle });
  await expect(childProposalDetail.getByText("父文档：分页填充-001")).toBeVisible();
  await childProposalDetail.getByRole("button", { name: "批准提案" }).click();
  await page.reload();
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  const parentTreeRow = page.locator(".document-link").filter({ hasText: "分页填充-001" });
  const childTreeRow = page.locator(".document-link").filter({ hasText: childTitle });
  await expect(parentTreeRow).toHaveAttribute("data-document-depth", "0");
  await expect(childTreeRow).toHaveAttribute("data-document-depth", "1");
  const treeOrder = await page.locator(".document-link").evaluateAll(rows => ({
    parent: rows.findIndex(row => row.textContent?.includes("分页填充-001")),
    child: rows.findIndex(row => row.textContent?.includes("分页树下的子文档")),
  }));
  expect(treeOrder.child).toBe(treeOrder.parent + 1);
  await childTreeRow.click();
  await expect(page.getByRole("heading", { name: childTitle })).toBeVisible();
  const grandchildTitle = "分页树下的孙文档";
  await page.locator(".toolbar-actions").getByRole("button", { name: `在“${childTitle}”下新建子文档` }).click();
  const grandchildDialog = page.getByRole("dialog");
  await expect(grandchildDialog.getByText(`父文档：${childTitle}`)).toBeVisible();
  await grandchildDialog.getByLabel("文档标题").fill(grandchildTitle);
  await grandchildDialog.getByLabel("Markdown 正文").fill("用于折叠树三级路径验证。");
  await grandchildDialog.getByRole("button", { name: "创建文档" }).click();
  await expect(page.locator(".toast[role=status]")).toContainText("子文档提案已提交");
  const childDocumentId = new URL(page.url()).searchParams.get("doc");
  expect(childDocumentId).toBeTruthy();
  await reviewerPage.goto(`/?team=${teamId}&space=${spaceId}&doc=${childDocumentId}`);
  await expect(reviewerPage.getByRole("heading", { name: childTitle })).toBeVisible();
  await reviewerPage.getByRole("button", { name: "提案审阅" }).click();
  const grandchildReviewPanel = reviewerPage.getByRole("region", { name: "提案审阅" });
  await grandchildReviewPanel.getByRole("button", { name: new RegExp(grandchildTitle) }).click();
  const grandchildProposalDetail = reviewerPage.getByRole("dialog", { name: grandchildTitle });
  await expect(grandchildProposalDetail.getByText(`父文档：${childTitle}`)).toBeVisible();
  await grandchildProposalDetail.getByRole("button", { name: "批准提案" }).click();
  await page.reload();
  await expect(page.getByRole("heading", { name: childTitle })).toBeVisible();
  const breadcrumb = page.getByRole("navigation", { name: "文档路径" });
  const breadcrumbSegments = breadcrumb.locator("[data-breadcrumb-segment], [data-breadcrumb-document], [data-breadcrumb-current]");
  const initialPath = await breadcrumbSegments.evaluateAll(nodes => nodes.map(node => node.textContent?.trim()));
  expect(initialPath).toEqual(["E2E 知识团队", "文档库使用说明", "分页填充-001", childTitle]);
  const parentCrumb = breadcrumb.getByRole("button", { name: "分页填充-001" });
  await parentCrumb.click();
  await expect(page.getByRole("heading", { name: "分页填充-001" })).toBeVisible();
  const parentDirectoryLinkForPath = page.locator(".document-child-directory").locator(".document-child-directory-link").filter({ hasText: childTitle });
  await parentDirectoryLinkForPath.click();
  await expect(page.getByRole("heading", { name: childTitle })).toBeVisible();
  const childDirectoryLinkForPath = page.locator(".document-child-directory").locator(".document-child-directory-link").filter({ hasText: grandchildTitle });
  await childDirectoryLinkForPath.click();
  await expect(page.getByRole("heading", { name: grandchildTitle })).toBeVisible();
  const grandchildId = new URL(page.url()).searchParams.get("doc");
  expect(grandchildId).toBeTruthy();
  const grandchildPath = await breadcrumbSegments.evaluateAll(nodes => nodes.map(node => node.textContent?.trim()));
  expect(grandchildPath).toEqual(["E2E 知识团队", "文档库使用说明", "分页填充-001", childTitle, grandchildTitle]);
  await page.screenshot({ path: "test-results/screenshots/document-breadcrumb-desktop.png" });
  await page.setViewportSize({ width: 375, height: 812 });
  const closeBreadcrumbMobileNav = page.getByRole("button", { name: "关闭导航" });
  if (await closeBreadcrumbMobileNav.isVisible()) await closeBreadcrumbMobileNav.click();
  await expect(closeBreadcrumbMobileNav).toBeHidden();
  await expect.poll(async () => { const box = await page.locator(".sidebar").boundingBox(); return box ? box.x + box.width : 0; }).toBeLessThanOrEqual(0);
  const breadcrumbCanReachSegment = async (selector: string) => breadcrumb.locator(selector).evaluate(element => {
    const viewport = element.closest(".breadcrumb-scroll")!.getBoundingClientRect();
    const segment = element.getBoundingClientRect();
    return segment.left >= viewport.left - 1 && segment.right <= viewport.right + 1;
  });
  await breadcrumb.evaluate(element => { element.scrollLeft = 0; });
  await expect.poll(() => breadcrumbCanReachSegment('[data-breadcrumb-segment="team"]')).toBe(true);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);
  await page.screenshot({ path: "test-results/screenshots/document-breadcrumb-mobile-375-start.png" });
  await breadcrumb.focus();
  await page.keyboard.press("End");
  await expect.poll(() => breadcrumbCanReachSegment("[data-breadcrumb-current]")).toBe(true);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);
  await page.screenshot({ path: "test-results/screenshots/document-breadcrumb-mobile-375-end.png" });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await parentCrumb.click();
  await expect(page.getByRole("heading", { name: "分页填充-001" })).toBeVisible();
  await parentDirectoryLinkForPath.click();
  await expect(page.getByRole("heading", { name: childTitle })).toBeVisible();
  await childDirectoryLinkForPath.click();
  await expect(page.getByRole("heading", { name: grandchildTitle })).toBeVisible();
  await page.getByRole("button", { name: "编辑文档" }).click();
  const breadcrumbTitleDraft = page.getByLabel("文档标题");
  await breadcrumbTitleDraft.fill("未发布的路径标题");
  await expect(breadcrumb.locator("[data-breadcrumb-current]")).toHaveText("未发布的路径标题");
  const cancelBreadcrumbNavigation = page.waitForEvent("dialog").then(async dialog => { expect(dialog.message()).toContain("未保存"); await dialog.dismiss(); });
  await Promise.all([cancelBreadcrumbNavigation, parentCrumb.click()]);
  await expect(page).toHaveURL(new RegExp(`doc=${grandchildId}`));
  await expect(breadcrumbTitleDraft).toHaveValue("未发布的路径标题");
  const acceptBreadcrumbNavigation = page.waitForEvent("dialog").then(async dialog => { expect(dialog.message()).toContain("未保存"); await dialog.accept(); });
  await Promise.all([acceptBreadcrumbNavigation, parentCrumb.click()]);
  await expect(page.getByRole("heading", { name: "分页填充-001" })).toBeVisible();
  await parentDirectoryLinkForPath.click();
  await expect(page.getByRole("heading", { name: childTitle })).toBeVisible();
  await page.locator(".document-child-directory").locator(".document-child-directory-link").filter({ hasText: grandchildTitle }).click();
  await expect(page.getByRole("heading", { name: grandchildTitle })).toBeVisible();
  await expect(page.getByRole("button", { name: "继续编辑草稿" })).toBeVisible();
  await expect(breadcrumb.locator("[data-breadcrumb-current]")).toHaveText(grandchildTitle);
  await page.getByRole("button", { name: "继续编辑草稿" }).click();
  await expect(page.getByLabel("文档标题")).toHaveValue("未发布的路径标题");
  await expect(breadcrumb.locator("[data-breadcrumb-current]")).toHaveText("未发布的路径标题");
  await page.getByLabel("文档标题").fill(grandchildTitle);
  await page.getByRole("button", { name: "返回查看" }).click();
  await expect(breadcrumb.locator("[data-breadcrumb-current]")).toHaveText(grandchildTitle);
  await breadcrumb.getByRole("button", { name: childTitle }).click();
  await expect(page.getByRole("heading", { name: childTitle })).toBeVisible();
  let releaseDirectoryLoad!: () => void;
  let directoryLoadObserved = false;
  let directoryRequestMode: "delay" | "fail" | "continue" = "delay";
  const directoryLoadGate = new Promise<void>(resolve => { releaseDirectoryLoad = resolve; });
  const directoryRouteMatcher = (url: URL) => url.pathname === `/api/spaces/${spaceId}/documents`;
  await page.route(directoryRouteMatcher, async route => {
    if (route.request().method() !== "GET" || Number(new URL(route.request().url()).searchParams.get("offset") ?? 0) !== 0) return route.continue();
    if (directoryRequestMode === "delay") {
      directoryRequestMode = "continue";
      const response = await route.fetch();
      directoryLoadObserved = true;
      await directoryLoadGate;
      return route.fulfill({ response });
    }
    if (directoryRequestMode === "fail") {
      directoryRequestMode = "continue";
      return route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: { code: "TEMPORARY_UNAVAILABLE", message: "temporary test failure" } }) });
    }
    return route.continue();
  });
  await page.reload();
  const childDirectory = page.locator(".document-child-directory");
  try {
    await expect.poll(() => directoryLoadObserved).toBe(true);
    await expect(breadcrumb.getByText("正在加载完整路径…")).toBeVisible();
    await expect(breadcrumb.getByRole("button", { name: "分页填充-001" })).toHaveCount(0);
    await expect(childDirectory.getByText("正在加载可见文档目录…")).toBeVisible();
    await expect(childDirectory.getByText(childTitle, { exact: true })).toHaveCount(0);
    await expect(childDirectory.getByText(grandchildTitle, { exact: true })).toHaveCount(0);
  } finally {
    releaseDirectoryLoad();
  }
  await expect(childDirectory.locator(".document-child-directory-link").filter({ hasText: grandchildTitle })).toBeVisible();
  directoryRequestMode = "fail";
  await page.reload();
  await expect(breadcrumb.getByText("完整路径加载失败")).toBeVisible();
  await expect(breadcrumb.getByRole("button", { name: "分页填充-001" })).toHaveCount(0);
  await expect(childDirectory.getByRole("alert")).toContainText("temporary test failure");
  await expect(childDirectory.getByText("暂无可见子文档。", { exact: true })).toHaveCount(0);
  await expect(childDirectory.getByText(childTitle, { exact: true })).toHaveCount(0);
  await expect(childDirectory.getByText(grandchildTitle, { exact: true })).toHaveCount(0);
  await childDirectory.getByRole("button", { name: "重试加载" }).click();
  await expect(childDirectory.locator(".document-child-directory-link").filter({ hasText: grandchildTitle })).toBeVisible();
  await expect(breadcrumb.getByRole("button", { name: "分页填充-001" })).toBeVisible();
  await page.unroute(directoryRouteMatcher);
  const currentParentRow = page.locator(".document-link").filter({ hasText: "分页填充-001" });
  const currentChildRow = page.locator(".document-link").filter({ hasText: childTitle });
  const currentGrandchildRow = page.locator(".document-link").filter({ hasText: grandchildTitle });
  await expect(currentParentRow).toHaveAttribute("data-document-depth", "0");
  await expect(currentChildRow).toHaveAttribute("data-document-depth", "1");
  await expect(currentGrandchildRow).toHaveAttribute("data-document-depth", "2");
  await expect(page.locator(".document-link").filter({ hasText: "分页填充-002" })).toBeVisible();

  await currentParentRow.click();
  await expect(page.getByRole("heading", { name: "分页填充-001" })).toBeVisible();
  const parentDirectory = page.locator(".document-child-directory");
  const childDirectoryLink = parentDirectory.locator(".document-child-directory-link").filter({ hasText: childTitle });
  const grandchildDirectoryLink = parentDirectory.locator(".document-child-directory-link").filter({ hasText: grandchildTitle });
  await expect(childDirectoryLink).toBeVisible();
  await expect(grandchildDirectoryLink).toBeVisible();
  const directoryTestToast = page.getByRole("button", { name: "关闭提示" });
  if (await directoryTestToast.isVisible()) await directoryTestToast.click();
  await page.screenshot({ path: "test-results/screenshots/document-child-directory-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 375, height: 812 });
  const mobileDrawerClose = page.locator(".mobile-close");
  if (await mobileDrawerClose.isVisible()) await mobileDrawerClose.click();
  await page.reload();
  await expect(page.getByRole("heading", { name: "分页填充-001" })).toBeVisible();
  await expect(parentDirectory.locator(".document-child-directory-link").filter({ hasText: grandchildTitle })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);
  await page.screenshot({ path: "test-results/screenshots/document-child-directory-mobile-375.png", fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  const parentDirectoryToggle = parentDirectory.getByRole("button", { name: "收起子文档目录" });
  await parentDirectoryToggle.click();
  await expect(parentDirectory.getByRole("button", { name: "展开子文档目录" })).toHaveAttribute("aria-expanded", "false");
  await expect(childDirectoryLink).toBeHidden();
  await parentDirectory.getByRole("button", { name: "展开子文档目录" }).click();
  const inlineChildToggle = parentDirectory.getByRole("button", { name: `折叠“${childTitle}”子文档` });
  await inlineChildToggle.click();
  await expect(grandchildDirectoryLink).toBeHidden();
  await expect(currentGrandchildRow).toBeVisible();
  await parentDirectory.getByRole("button", { name: `展开“${childTitle}”子文档` }).click();
  await expect(grandchildDirectoryLink).toBeVisible();
  await page.getByRole("button", { name: "折叠“分页填充-001”子文档" }).click();
  await expect(currentChildRow).toBeHidden();
  await expect(childDirectoryLink).toBeVisible();
  await page.getByRole("button", { name: "展开“分页填充-001”子文档" }).click();
  await childDirectoryLink.click();
  await expect(page.getByRole("heading", { name: childTitle })).toBeVisible();
  await expect(page.locator(".document-child-directory").locator(".document-child-directory-link").filter({ hasText: grandchildTitle })).toBeVisible();

  const parentTreeToggle = page.getByRole("button", { name: "折叠“分页填充-001”子文档" });
  const childTreeToggle = page.getByRole("button", { name: `折叠“${childTitle}”子文档` });
  await parentTreeToggle.focus();
  await page.keyboard.press("Space");
  await expect(page.getByRole("button", { name: "展开“分页填充-001”子文档" })).toHaveAttribute("aria-expanded", "false");
  await expect(currentChildRow).toBeHidden();
  await expect(currentGrandchildRow).toBeHidden();
  await expect(page.locator(".document-link").filter({ hasText: "分页填充-002" })).toBeVisible();
  await page.getByRole("button", { name: "展开“分页填充-001”子文档" }).click();
  await expect(currentChildRow).toBeVisible();
  await childTreeToggle.click();
  await expect(page.getByRole("button", { name: `展开“${childTitle}”子文档` })).toHaveAttribute("aria-expanded", "false");
  await expect(currentGrandchildRow).toBeHidden();
  await page.getByRole("button", { name: `展开“${childTitle}”子文档` }).click();
  await expect(currentGrandchildRow).toBeVisible();

  await page.getByRole("button", { name: "折叠“分页填充-001”子文档" }).click();
  const searchBox = page.getByRole("textbox", { name: "搜索团队文档" });
  await searchBox.fill(grandchildTitle);
  const searchedGrandchild = page.locator(".document-link").filter({ hasText: grandchildTitle });
  await expect(searchedGrandchild).toBeVisible();
  await expect(searchedGrandchild).toHaveAttribute("data-document-depth", "0");
  await expect(page.locator(".document-tree-toggle")).toHaveCount(0);
  await searchBox.fill("");
  await expect(page.getByRole("button", { name: "展开“分页填充-001”子文档" })).toHaveAttribute("aria-expanded", "false");
  await expect(currentGrandchildRow).toBeHidden();
  const urlBeforeSpaceSwitch = page.url();
  await page.locator(".space-link").filter({ hasText: "团队知识库" }).click();
  await expect(page.locator(".doc-nav-title h1")).toHaveText("团队知识库");
  expect(new URL(page.url()).searchParams.get("doc")).toBeNull();
  expect(new URL(page.url()).searchParams.get("team")).toBe(new URL(urlBeforeSpaceSwitch).searchParams.get("team"));
  expect(new URL(page.url()).searchParams.get("space")).toBe(new URL(urlBeforeSpaceSwitch).searchParams.get("space"));
  await expect(page.getByText("访问权限或文档状态已变化")).toHaveCount(0);
  await page.locator(".space-link").filter({ hasText: "文档库使用说明" }).click();
  await expect(page.locator(".doc-nav-title h1")).toHaveText("文档库使用说明");
  await expect(page.getByRole("button", { name: "折叠“分页填充-001”子文档" })).toBeVisible();
  await expect(currentGrandchildRow).toBeVisible();

  await page.locator(".document-link").filter({ hasText: childTitle }).click();
  await expect(page.getByRole("heading", { name: childTitle })).toBeVisible();
  await enterDocumentEdit(page);
  const treeDraft = page.getByLabel("Markdown 正文");
  const savedChildBody = await treeDraft.inputValue();
  await treeDraft.fill(savedChildBody + "\n\n折叠时保留的未保存草稿。");
  const pageUrlBeforeFold = page.url();
  let unexpectedFoldDialog: string | null = null;
  const onUnexpectedFoldDialog = async (dialog: import("@playwright/test").Dialog) => { unexpectedFoldDialog = dialog.message(); await dialog.dismiss(); };
  page.on("dialog", onUnexpectedFoldDialog);
  try {
    await page.getByRole("button", { name: "折叠“分页填充-001”子文档" }).click();
  } finally {
    page.off("dialog", onUnexpectedFoldDialog);
  }
  expect(unexpectedFoldDialog).toBeNull();
  expect(page.url()).toBe(pageUrlBeforeFold);
  await expect(treeDraft).toHaveValue(/折叠时保留的未保存草稿/);
  const cancelSpaceSwitch = page.waitForEvent("dialog").then(async dialog => {
    expect(dialog.message()).toContain("未保存的修改");
    await dialog.dismiss();
  });
  await Promise.all([cancelSpaceSwitch, page.locator(".space-link").filter({ hasText: "团队知识库" }).click()]);
  expect(page.url()).toBe(pageUrlBeforeFold);
  await expect(treeDraft).toHaveValue(/折叠时保留的未保存草稿/);
  const acceptSpaceSwitch = page.waitForEvent("dialog").then(async dialog => {
    expect(dialog.message()).toContain("未保存的修改");
    await dialog.accept();
  });
  await Promise.all([acceptSpaceSwitch, page.locator(".space-link").filter({ hasText: "团队知识库" }).click()]);
  await expect(page.locator(".doc-nav-title h1")).toHaveText("团队知识库");
  expect(new URL(page.url()).searchParams.get("doc")).toBeNull();
  await expect(page.getByText("访问权限或文档状态已变化")).toHaveCount(0);
  await page.locator(".space-link").filter({ hasText: "文档库使用说明" }).click();
  await expect(page.locator(".doc-nav-title h1")).toHaveText("文档库使用说明");
  await page.locator(".document-link").filter({ hasText: childTitle }).click();
  await expect(page.getByRole("heading", { name: childTitle })).toBeVisible();
  await enterDocumentEdit(page);
  await expect(page.getByLabel("Markdown 正文")).toHaveValue(/折叠时保留的未保存草稿/);
  await treeDraft.fill(savedChildBody);
  await page.getByRole("button", { name: "返回查看" }).click();
  await expect(page.getByRole("button", { name: "折叠“分页填充-001”子文档" })).toHaveAttribute("aria-expanded", "true");
  await expect(currentGrandchildRow).toBeVisible();

  await childTreeRow.scrollIntoViewIfNeeded();
  await page.screenshot({ path: "test-results/screenshots/document-tree-desktop.png" });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.getByRole("button", { name: "打开文档列表" }).click();
  await expect(page.locator(".doc-nav")).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);
  await childTreeRow.scrollIntoViewIfNeeded();
  const mobileParentToggle = page.getByRole("button", { name: "折叠“分页填充-001”子文档" });
  const mobileChildToggle = page.getByRole("button", { name: `折叠“${childTitle}”子文档` });
  await expect(mobileParentToggle).toBeVisible();
  await expect(mobileChildToggle).toBeVisible();
  const mobileParentToggleBox = await mobileParentToggle.boundingBox();
  const mobileChildToggleBox = await mobileChildToggle.boundingBox();
  expect(mobileParentToggleBox).not.toBeNull();
  expect(mobileChildToggleBox).not.toBeNull();
  expect(mobileChildToggleBox!.x).toBeGreaterThan(mobileParentToggleBox!.x);
  await expect(differentParentAction).toBeVisible();
  await expect(differentParentAction.locator("svg")).toBeVisible();
  await page.screenshot({ path: "test-results/screenshots/document-tree-mobile-375.png" });
  await page.getByRole("button", { name: "返回文档正文" }).click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await parentTreeRow.click();
  await expect(page.getByRole("heading", { name: "分页填充-001" })).toBeVisible();
  await page.getByRole("button", { name: "删除文档" }).click();
  await expect(page.locator(".toast[role=status]")).toContainText("包含 1 个子文档，不能删除");
  await page.locator(".document-link").filter({ hasText: "团队公开说明" }).click();
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await enterDocumentEdit(page);
  const proposalEditor = page.getByLabel("Markdown 正文");
  await proposalEditor.fill((await proposalEditor.inputValue()) + "\n\n提交审核的内容");
  await page.getByRole("button", { name: "保存", exact: true }).click();
  await expect(page.locator(".toast[role=status]")).toContainText("更新提案已提交");
  const pendingPublished = await page.evaluate(async id => (await (await fetch(`/api/documents/${id}`, { credentials: "same-origin" })).json()).document, publicDocId);
  expect(pendingPublished.body).not.toContain("提交审核的内容");

  await reviewerPage.goto(`/?team=${teamId}&space=${spaceId}&doc=${publicDocId}`);
  await expect(reviewerPage.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await reviewerPage.getByRole("button", { name: "提案审阅" }).click();
  const reviewPanel = reviewerPage.getByRole("region", { name: "提案审阅" });
  await expect(reviewPanel.getByRole("heading", { name: "提案审阅" })).toBeVisible();
  await reviewPanel.getByRole("button", { name: /团队公开说明.*E2E 管理员.*更新文档/ }).click();
  const proposalDetail = reviewerPage.getByRole("dialog", { name: "团队公开说明" });
  await expect(proposalDetail.getByText(/基于版本：2/)).toBeVisible();
  await reviewerPage.screenshot({ path: "docs/images/teamshelf-review-demo.png", animations: "disabled" });
  await proposalDetail.getByRole("button", { name: "批准提案" }).click();
  await expect.poll(async () => (await page.evaluate(async id => (await (await fetch(`/api/documents/${id}`, { credentials: "same-origin" })).json()).document.body, publicDocId))).toContain("提交审核的内容");
  await page.reload();
  await expect(page.locator(".markdown-preview")).toContainText("提交审核的内容");
  await page.getByRole("button", { name: "知识库审阅规则" }).click();
  const disableReviewDialog = page.getByRole("dialog", { name: "变更审阅规则" });
  await disableReviewDialog.getByLabel("所有文档变更都需其他管理员批准").uncheck();
  await disableReviewDialog.getByRole("button", { name: "保存规则" }).click();
  await expect(page.locator(".toast[role=status]")).toContainText("已关闭提交审阅");
  // Two real browser sessions edit both supported collaborative modes. Fast typing must not hit the WS frame limit.
  await enterDocumentEdit(page);
  await page.getByRole("button", { name: "协作草稿" }).click();
  let collab = page.getByRole("dialog", { name: "多人协作草稿" });
  await collab.getByRole("button", { name: "创建 Markdown 协作草稿" }).click();
  await expect(collab.locator(".collab-editor [role=status]")).toContainText("已连接", { timeout: 15000 });
  await page.screenshot({ path: "docs/images/teamshelf-collaboration-demo.png", animations: "disabled" });
  await expect(collab.locator(".collab-source-editor")).toBeVisible({ timeout: 10000 });
  await reviewerPage.goto(`/?team=${teamId}&space=${spaceId}&doc=${publicDocId}`);
  await expect(reviewerPage.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await enterDocumentEdit(reviewerPage);
  await enterDocumentEdit(reviewerPage);
  await reviewerPage.getByRole("button", { name: "协作草稿" }).click();
  const reviewerCollab = reviewerPage.getByRole("dialog", { name: "多人协作草稿" });
  await expect(reviewerCollab.locator(".collab-editor [role=status]")).toContainText("已连接", { timeout: 15000 });
  const mdFast = " 双人实时协作连续输入超过四十个字符来验证同步是否稳定，并观察正常快速键入时有没有触发服务端帧数限制";
  const ownerMarkdown = collab.locator(".collab-source-editor .cm-content");
  await ownerMarkdown.click();
  await page.keyboard.type(mdFast, { delay: 8 });
  await expect(reviewerCollab.locator(".collab-source-editor .cm-content")).toContainText(mdFast, { timeout: 15000 });
  await expect(collab.locator(".collab-editor [role=status]")).toContainText("已连接");
  const concurrentPublish = await page.evaluate(async id => {
    const current = (await (await fetch("/api/documents/" + id)).json()).document;
    const response = await fetch("/api/documents/" + id, { method: "PATCH", headers: { "Content-Type": "application/json", "X-Requested-With": "TeamShelf" }, body: JSON.stringify({ title: current.title, body: current.body + "\n\n并发正式更新", version: current.version }) });
    return response.status;
  }, publicDocId);
  expect(concurrentPublish).toBe(200);
  await collab.getByRole("button", { name: "发布 / 提交审核" }).click();
  const rebaseRegion = collab.getByRole("region", { name: "同步草稿基线确认" });
  await expect(rebaseRegion).toBeVisible();
  await expect(rebaseRegion).toContainText("并发正式更新");
  await expect(rebaseRegion).toContainText(mdFast.trim());
  await rebaseRegion.getByRole("button", { name: /以版本 \d+ 为新基线，保留当前草稿/ }).click();
  await expect(collab.getByText(/协作内容完整保留/)).toBeVisible();
  await expect(ownerMarkdown).toContainText(mdFast);
  await collab.getByRole("button", { name: "发布 / 提交审核" }).click();
  await expect(collab.locator(".collab-finished strong")).toBeVisible({ timeout: 15000 });
  const markdownCollabSaved = await page.evaluate(async id => (await (await fetch(`/api/documents/${id}`)).json()).document.body, publicDocId);
  expect(markdownCollabSaved).toContain(mdFast.trim());
  await collab.getByRole("button", { name: "关闭", exact: true }).click();
  await expect(reviewerPage.getByRole("dialog", { name: "多人协作草稿" })).toHaveCount(0);

  await enterDocumentEdit(page);
  await page.getByRole("button", { name: "协作草稿" }).click();
  collab = page.getByRole("dialog", { name: "多人协作草稿" });
  await collab.getByRole("button", { name: "创建富文本协作草稿" }).click();
  await expect(collab.locator(".collab-editor [role=status]")).toContainText("已连接", { timeout: 15000 });
  await page.screenshot({ path: "docs/images/teamshelf-collaboration-demo.png", animations: "disabled" });
  await expect(collab.locator(".collab-rich-editor")).toBeVisible({ timeout: 10000 });
  await enterDocumentEdit(reviewerPage);
  await reviewerPage.getByRole("button", { name: "协作草稿" }).click();
  const reviewerRichCollab = reviewerPage.getByRole("dialog", { name: "多人协作草稿" });
  await expect(reviewerRichCollab.locator(".collab-editor [role=status]")).toContainText("已连接", { timeout: 15000 });
  const richFast = " 富文本双人协作快速输入超过四十个字符，验证实时光标、远端内容同步和正常输入时的帧数限制是否合理";
  const ownerRich = collab.locator(".collab-rich-editor .ProseMirror");
  await ownerRich.click(); await page.keyboard.press("End"); await page.keyboard.type(richFast, { delay: 8 });
  await expect(reviewerRichCollab.locator(".collab-rich-editor .ProseMirror")).toContainText(richFast, { timeout: 15000 });
  await expect(collab.locator(".collab-editor [role=status]")).toContainText("已连接");
  await collab.getByRole("button", { name: "发布 / 提交审核" }).click();
  await expect(collab.locator(".collab-finished strong")).toBeVisible({ timeout: 15000 });
  const richCollabSaved = await page.evaluate(async id => (await (await fetch(`/api/documents/${id}`)).json()).document.body, publicDocId);
  expect(richCollabSaved).toContain(richFast.trim());
  expect(richCollabSaved).toContain(mdFast.trim());
  await collab.getByRole("button", { name: "关闭", exact: true }).click();
  await expect(reviewerPage.getByRole("dialog", { name: "多人协作草稿" })).toHaveCount(0);
  await reviewerContext.close();
  let releaseSpaceAccess!: () => void;
  let announceSpaceAccessRead!: () => void;
  const spaceAccessGate = new Promise<void>(resolve => { releaseSpaceAccess = resolve; });
  const spaceAccessStarted = new Promise<void>(resolve => { announceSpaceAccessRead = resolve; });
  await page.route(`**/api/spaces/${spaceId}/access`, async route => { if (route.request().method() === "GET") { const response = await route.fetch(); announceSpaceAccessRead(); await spaceAccessGate; await route.fulfill({ response }); } else await route.continue(); });
  await page.getByRole("button", { name: "知识库访问权限" }).click();
  let spaceAccessDialog = page.getByRole("dialog");
  await expect(spaceAccessDialog.getByLabel("访问范围")).toBeDisabled();
  await spaceAccessStarted;
  await spaceAccessDialog.getByRole("button", { name: "关闭对话框" }).click();
  await page.getByRole("button", { name: "访问权限", exact: true }).click();
  const documentAccessDialog = page.getByRole("dialog");
  const documentAccessRange = documentAccessDialog.getByLabel("访问范围");
  await expect(documentAccessRange).toBeEnabled();
  await expect(documentAccessRange).toHaveValue("inherit");
  releaseSpaceAccess();
  await expect(documentAccessRange).toHaveValue("inherit");
  await documentAccessDialog.getByRole("button", { name: "关闭对话框" }).click();
  await page.unroute(`**/api/spaces/${spaceId}/access`);
  await page.getByRole("button", { name: "知识库访问权限" }).click();
  spaceAccessDialog = page.getByRole("dialog");
  await expect(spaceAccessDialog.getByLabel("访问范围")).toBeEnabled();
  await spaceAccessDialog.getByLabel("访问范围").selectOption("team");
  await spaceAccessDialog.getByRole("button", { name: "解释与预览" }).first().click();
  const spaceImpact = page.getByRole("dialog", { name: "访问解释与变更预览" });
  await expect(spaceImpact).toBeVisible();
  await expect(spaceImpact).toContainText("权限结果来自服务端当前策略");
  await page.screenshot({ path: "docs/images/teamshelf-permissions-demo.png", animations: "disabled" });
  await spaceImpact.getByRole("button", { name: "确认并应用" }).click();
  await expect(page.getByText("访问权限已更新。" )).toBeVisible();

  await page.getByRole("button", { name: "新建文档" }).click();
  createDialog = page.getByRole("dialog");
  const publicDocIdBeforeRestricted = new URL(page.url()).searchParams.get("doc");
  await createDialog.getByLabel("文档标题").fill("受限项目计划");
  await createDialog.getByLabel("Markdown 正文").fill("内部计划，仅读者授权后可见。");
  await createDialog.getByRole("button", { name: "创建文档" }).click();
  const restrictedDocId = await waitForNewDocumentUrl(page, publicDocIdBeforeRestricted);
  expect(restrictedDocId).toBeTruthy();
  let releaseAccessRead!: () => void;
  const accessReadGate = new Promise<void>(resolve => { releaseAccessRead = resolve; });
  await page.route(`**/api/documents/${restrictedDocId}/access`, async route => { if (route.request().method() === "GET") { const response = await route.fetch(); await accessReadGate; await route.fulfill({ response }); } else await route.continue(); });
  await page.getByRole("button", { name: "访问权限", exact: true }).click();
  const accessDialog = page.getByRole("dialog");
  const accessRange = accessDialog.getByLabel("访问范围");
  await expect(accessRange).toBeDisabled();
  await expect(accessDialog.getByRole("button", { name: "解释与预览" }).first()).toBeDisabled();
  releaseAccessRead();
  await expect(accessRange).toBeEnabled();
  await accessRange.selectOption("restricted");
  await accessDialog.screenshot({ path: "docs/MCP/images/admin-document-permissions.png", animations: "disabled" });
  await expect(accessRange).toHaveValue("restricted");
  const aclPutWait = page.waitForResponse(response => response.url().includes(`/api/documents/${restrictedDocId}/access`) && response.request().method() === "PUT");
  await accessDialog.getByRole("button", { name: "解释与预览" }).first().click();
  const aclPreview = page.getByRole("dialog", { name: "访问解释与变更预览" });
  await expect(aclPreview).toBeVisible();
  await expect(aclPreview).toContainText("受影响成员与文档");
  await expect(aclPreview).toContainText("E2E 阅读者");
  await page.screenshot({ path: "docs/images/teamshelf-permissions-demo.png", animations: "disabled" });
  await aclPreview.getByRole("button", { name: "确认并应用" }).click();
  const aclPutResponse = await aclPutWait;
  expect(aclPutResponse.status()).toBe(200);
  expect(aclPutResponse.request().postDataJSON()).toEqual({ visibility: "restricted", grants: [] });
  const aclPutBody = await aclPutResponse.json();
  expect(aclPutBody.document.visibility).toBe("restricted");
  await expect(page.getByText("访问权限已更新。" )).toBeVisible();

  const viewerRestrictedRead = await viewerMcp.callTool({ name: "get_document", arguments: { documentId: restrictedDocId } });
  expect(viewerRestrictedRead.isError).toBe(true);
  expect(JSON.stringify(viewerRestrictedRead)).not.toContain("内部计划，仅读者授权后可见。");
  const viewerMcpUserId = await viewerPage.evaluate(async () => (await (await fetch("/api/auth/me", { credentials: "same-origin" })).json()).user.id as string);
  const grantViewerStatus = await page.evaluate(async ({ documentId, userId }) => (await fetch(`/api/documents/${documentId}/access`, {
    method: "PUT", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-Requested-With": "TeamShelf" },
    body: JSON.stringify({ visibility: "restricted", grants: [{ userId, role: "viewer" }] }),
  })).status, { documentId: restrictedDocId, userId: viewerMcpUserId });
  expect(grantViewerStatus).toBe(200);
  const viewerAllowedAfterGrant = await viewerMcp.callTool({ name: "get_document", arguments: { documentId: restrictedDocId } });
  expect(viewerAllowedAfterGrant.isError).not.toBe(true);
  expect(JSON.stringify(viewerAllowedAfterGrant)).toContain("内部计划，仅读者授权后可见。");
  const revokeViewerStatus = await page.evaluate(async documentId => (await fetch(`/api/documents/${documentId}/access`, {
    method: "PUT", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-Requested-With": "TeamShelf" },
    body: JSON.stringify({ visibility: "restricted", grants: [] }),
  })).status, restrictedDocId);
  expect(revokeViewerStatus).toBe(200);
  const viewerDeniedAfterRevoke = await viewerMcp.callTool({ name: "get_document", arguments: { documentId: restrictedDocId } });
  expect(viewerDeniedAfterRevoke.isError).toBe(true);
  expect(JSON.stringify(viewerDeniedAfterRevoke)).not.toContain("内部计划，仅读者授权后可见。");
  await viewerMcp.close();

  await page.getByRole("button", { name: "新建文档" }).click();
  createDialog = page.getByRole("dialog");
  const restrictedDocIdBeforeDelayed = restrictedDocId;
  await createDialog.getByLabel("文档标题").fill("延迟响应目标");
  await createDialog.getByLabel("Markdown 正文").fill("登出竞态的目标文档。");
  await createDialog.getByRole("button", { name: "创建文档" }).click();
  const delayedDocId = await waitForNewDocumentUrl(page, restrictedDocIdBeforeDelayed);
  expect(delayedDocId).toBeTruthy();

  await page.getByRole("button", { name: "新建文档" }).click();
  createDialog = page.getByRole("dialog");
  const delayedDocIdBeforeRich = delayedDocId;
  await createDialog.getByLabel("文档标题").fill("富文本保护测试");
  await createDialog.getByLabel("Markdown 正文").fill("安全保护源稿。");
  await createDialog.getByRole("button", { name: "创建文档" }).click();
  const tableDocId = await waitForNewDocumentUrl(page, delayedDocIdBeforeRich);
  await page.getByRole("tab", { name: "富文本" }).click();
  const richParagraph = page.locator(".ProseMirror p").first();
  await richParagraph.click(); await page.keyboard.press("End"); await page.keyboard.press("Shift+Enter");
  await expect(page.locator(".ProseMirror p br")).toHaveCount(2);
  await expect(page.getByRole("button", { name: "保存", exact: true })).toBeDisabled();
  await expect(page.getByText(/无法安全导出为 Markdown/)).toBeVisible();
  const [richDownload] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: "下载富文本草稿" }).click()]);
  expect(richDownload.suggestedFilename()).toBe("teamshelf-rich-draft.json");
  const unchanged = await page.evaluate(async id => (await (await fetch(`/api/documents/${id}`, { credentials: "same-origin" })).json()).document, tableDocId);
  expect(unchanged.body).toBe("安全保护源稿。");
  page.once("dialog", dialog => dialog.accept());
  await page.goto(`/?team=${teamId}&space=${spaceId}&doc=${publicDocId}`);
  const publicUrl = `/?team=${teamId}&space=${spaceId}&doc=${publicDocId}`;
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await page.locator(".toolbar-actions").getByRole("button", { name: "在“团队公开说明”下新建子文档" }).click();
  const restrictedChildDialog = page.getByRole("dialog");
  await expect(restrictedChildDialog.getByText("父文档：团队公开说明")).toBeVisible();
  const publicDocIdBeforeRestrictedChild = new URL(page.url()).searchParams.get("doc");
  await restrictedChildDialog.getByLabel("文档标题").fill("受限目录子项");
  await restrictedChildDialog.getByLabel("Markdown 正文").fill("仅测试可见目录的ACL过滤。");
  await restrictedChildDialog.getByRole("button", { name: "创建文档" }).click();
  const restrictedChildId = await waitForNewDocumentUrl(page, publicDocIdBeforeRestrictedChild);
  const restrictedChildAccess = await page.evaluate(async id => {
    const response = await fetch(`/api/documents/${id}/access`, { method: "PUT", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-Requested-With": "TeamShelf" }, body: JSON.stringify({ visibility: "restricted", grants: [] }) });
    return { status: response.status, body: await response.json() };
  }, restrictedChildId);
  expect(restrictedChildAccess.status).toBe(200);
  await page.goto(publicUrl);
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await viewerPage.goto(publicUrl);
  await expect(viewerPage.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  const viewerChildDirectory = viewerPage.locator(".document-child-directory");
  await expect(viewerChildDirectory.getByText("暂无可见子文档。", { exact: true })).toBeVisible();
  await expect(viewerChildDirectory.getByText("受限目录子项", { exact: true })).toHaveCount(0);
  await expect(viewerPage.getByRole("button", { name: "编辑文档" })).toHaveCount(0);
  await expect(viewerPage.getByRole("button", { name: "继续编辑草稿" })).toHaveCount(0);
  await expect(viewerPage.getByLabel("Markdown 正文")).toHaveCount(0);
  await expect(viewerPage.locator(".document-child-create")).toHaveCount(0);
  await expect(viewerPage.locator(".toolbar-actions .child-document-button")).toHaveCount(0);
  await expect(viewerPage.getByRole("button", { name: "新建文档" })).toHaveCount(0);
  await expect(viewerPage.getByRole("button", { name: "保存", exact: true })).toHaveCount(0);
  await expect(viewerPage.locator(".markdown-preview")).toContainText("安全编辑");
  const viewerId = await viewerPage.evaluate(async () => (await (await fetch("/api/auth/me", { credentials: "same-origin" })).json()).user.id as string);
  await viewerPage.evaluate(({ userId, documentId }) => sessionStorage.setItem(`teamshelf:draft:${userId}:${documentId}`, JSON.stringify({ title: "只读不可见草稿标题", body: "只读不可见草稿正文" })), { userId: viewerId, documentId: publicDocId! });
  await viewerPage.reload();
  await expect(viewerPage.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await expect(viewerPage.getByText("此设备存在未发布草稿，但当前账号没有编辑权限；草稿内容不会显示。", { exact: true })).toBeVisible();
  await expect(viewerPage.getByText("只读不可见草稿正文", { exact: true })).toHaveCount(0);
  await expect(viewerPage.getByRole("button", { name: "继续编辑草稿" })).toHaveCount(0);
  const grandchildDocumentId = await page.evaluate(async ({ spaceId, title }) => {
    const result = await (await fetch(`/api/spaces/${spaceId}/documents?offset=0&limit=100`, { credentials: "same-origin" })).json();
    return result.documents.find((document: any) => document.title === title)?.id ?? null;
  }, { spaceId, title: grandchildTitle });
  expect(grandchildDocumentId).toBeTruthy();
  await viewerPage.goto(`/?team=${teamId}&space=${spaceId}&doc=${grandchildDocumentId}`);
  await expect(viewerPage.getByRole("heading", { name: grandchildTitle })).toBeVisible();
  const viewerParentToggle = viewerPage.getByRole("button", { name: "折叠“分页填充-001”子文档" });
  await expect(viewerParentToggle).toBeVisible();
  await expect(viewerPage.locator(".document-child-create")).toHaveCount(0);
  await viewerParentToggle.click();
  await expect(viewerPage.locator(".document-link").filter({ hasText: childTitle })).toBeHidden();
  await expect(viewerPage.locator(".document-link").filter({ hasText: grandchildTitle })).toBeHidden();
  await expect(viewerPage.getByRole("button", { name: "展开“分页填充-001”子文档" })).toHaveAttribute("aria-expanded", "false");
  await viewerPage.getByRole("button", { name: "展开“分页填充-001”子文档" }).click();
  await expect(viewerPage.locator(".document-link").filter({ hasText: grandchildTitle })).toBeVisible();
  await viewerPage.goto(publicUrl);
  await expect(viewerPage.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await viewerPage.screenshot({ path: "test-results/teamshelf-desktop.png", fullPage: true });
  await viewerPage.setViewportSize({ width: 375, height: 812 });
  const openMobileNav = viewerPage.getByRole("button", { name: "打开团队侧栏" });
  await expect(openMobileNav).toBeVisible();
  await expect(viewerPage.locator(".mobile-close")).toBeHidden();
  await openMobileNav.click();
  const closeMobileNav = viewerPage.getByRole("button", { name: "关闭导航" });
  await expect(closeMobileNav).toBeVisible();
  await expect.poll(async () => (await closeMobileNav.boundingBox())?.x ?? -1).toBeGreaterThanOrEqual(0);
  const closeRect = await closeMobileNav.boundingBox();
  expect(closeRect).not.toBeNull();
  expect(closeRect!.x + closeRect!.width).toBeLessThanOrEqual(375);
  await closeMobileNav.click();
  await expect(closeMobileNav).toBeHidden();
  await expect.poll(async () => { const box = await viewerPage.locator(".sidebar").boundingBox(); return box ? box.x + box.width : 0; }).toBeLessThanOrEqual(0);
  await expect.poll(() => viewerPage.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);
  const mobileDocToggle = viewerPage.getByRole("button", { name: "打开文档列表" });
  await expect(mobileDocToggle).toBeVisible();
  await mobileDocToggle.click();
  await expect(viewerPage.locator(".doc-nav")).toBeVisible();
  await expect(viewerPage.locator(".published-title")).toBeHidden();
  await expect.poll(() => viewerPage.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);
  await viewerPage.screenshot({ path: "test-results/screenshots/document-list-mobile-375.png" });
  await viewerPage.getByRole("button", { name: "返回文档正文" }).click();
  await expect(viewerPage.locator(".published-title")).toBeVisible();
  await expect.poll(() => viewerPage.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);
  await viewerPage.screenshot({ path: "test-results/teamshelf-mobile-375.png", fullPage: true });

  let aclEvidence = await page.evaluate(async id => { const response = await fetch(`/api/documents/${id}/access`, { credentials: "same-origin" }); return { status: response.status, retryAfter: response.headers.get("retry-after"), body: await response.json() }; }, restrictedDocId);
  if (aclEvidence.status === 429 && aclEvidence.body.error?.code === "RATE_LIMITED") {
    const retryAfterSeconds = aclEvidence.retryAfter && /^\d+$/.test(aclEvidence.retryAfter) ? Number(aclEvidence.retryAfter) : NaN;
    expect(Number.isInteger(retryAfterSeconds) && retryAfterSeconds > 0 && retryAfterSeconds <= 60, `Unexpected Retry-After value: ${aclEvidence.retryAfter}`).toBe(true);
    await page.waitForTimeout((retryAfterSeconds + 1) * 1000);
    aclEvidence = await page.evaluate(async id => { const response = await fetch(`/api/documents/${id}/access`, { credentials: "same-origin" }); return { status: response.status, retryAfter: response.headers.get("retry-after"), body: await response.json() }; }, restrictedDocId);
  }
  let viewerAuthEvidence = await viewerPage.evaluate(async () => {
    const response = await fetch("/api/auth/me", { credentials: "same-origin" });
    const body = await response.json();
    return { status: response.status, errorCode: body.error?.code as string | undefined, retryAfter: response.headers.get("retry-after"), user: body.user && { id: body.user.id, email: body.user.email }, teams: body.teams?.map((t: any) => ({ id: t.id, role: t.role })) };
  });
  if (viewerAuthEvidence.status === 429 && viewerAuthEvidence.errorCode === "RATE_LIMITED") {
    const retryAfterSeconds = viewerAuthEvidence.retryAfter && /^\d+$/.test(viewerAuthEvidence.retryAfter) ? Number(viewerAuthEvidence.retryAfter) : NaN;
    expect(Number.isInteger(retryAfterSeconds) && retryAfterSeconds > 0 && retryAfterSeconds <= 60, `Unexpected Retry-After value: ${viewerAuthEvidence.retryAfter}`).toBe(true);
    await viewerPage.waitForTimeout((retryAfterSeconds + 1) * 1000);
    viewerAuthEvidence = await viewerPage.evaluate(async () => {
      const response = await fetch("/api/auth/me", { credentials: "same-origin" });
      const body = await response.json();
      return { status: response.status, errorCode: body.error?.code as string | undefined, retryAfter: response.headers.get("retry-after"), user: body.user && { id: body.user.id, email: body.user.email }, teams: body.teams?.map((t: any) => ({ id: t.id, role: t.role })) };
    });
  }
  const viewerEvidence = await viewerPage.evaluate(async id => { const response = await fetch(`/api/documents/${id}`, { credentials: "same-origin" }); const body = await response.json(); return { documentStatus: response.status, document: body.document && { id: body.document.id, spaceId: body.document.spaceId, title: body.document.title, visibility: body.document.visibility, grants: body.document.grants, body: body.document.body } }; }, restrictedDocId);
  expect(aclEvidence.status).toBe(200);
  expect(aclEvidence.body).toEqual({ visibility: "restricted", grants: [] });
  expect(viewerAuthEvidence.status).toBe(200);
  expect(viewerAuthEvidence.teams).toContainEqual({ id: teamId, role: "viewer" });
  expect(viewerEvidence.documentStatus).toBe(404);
  expect(viewerEvidence.document).toBeUndefined();
  const restrictedUrl = `/?team=${teamId}&space=${spaceId}&doc=${restrictedDocId}`;
  await viewerPage.goto(restrictedUrl);
  await expect(viewerPage.getByText("访问权限或文档状态已变化")).toBeVisible();
  await expect(viewerPage.getByText("受限项目计划")).toHaveCount(0);
  const forbidden = await viewerPage.evaluate(async id => (await fetch(`/api/documents/${id}`, { credentials: "same-origin" })).status, restrictedDocId);
  expect(forbidden).toBe(404);

  await page.goto(publicUrl);
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await enterDocumentEdit(page);
  await page.getByRole("tab", { name: "源码" }).click();
  const source = page.getByLabel("Markdown 正文");
  await source.fill("# 本地草稿\n\n保留在浏览器会话中。\n");
  const responseStatus = await page.evaluate(async id => {
    const current = await (await fetch(`/api/documents/${id}`, { credentials: "same-origin" })).json();
    const result = await fetch(`/api/documents/${id}`, { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-Requested-With": "TeamShelf" }, body: JSON.stringify({ title: current.document.title, body: `${current.document.body}\n并发服务器修改`, version: current.document.version }) });
    return result.status;
  }, publicDocId);
  expect(responseStatus).toBe(200);
  await page.getByRole("button", { name: "保存", exact: true }).click();
  await expect(page.getByText(/保存时发现新版本/)).toBeVisible();
  await expect(page.getByRole("button", { name: "下载草稿" })).toBeVisible();
  await expect(source).toHaveValue(/本地草稿/);

  page.once("dialog", dialog => dialog.accept());
  await page.reload();
  await expect(page.getByRole("heading", { name: "团队公开说明" })).toBeVisible();
  await expect(page.getByText("此设备保存有未发布的本地草稿。查看内容仍是已发布版本。", { exact: false })).toBeVisible();
  await expect(page.getByLabel("Markdown 正文")).toHaveCount(0);
  await page.getByRole("button", { name: "继续编辑草稿" }).click();
  await expect(page.getByLabel("Markdown 正文")).toHaveValue(/本地草稿/);
  await expect(page).toHaveURL(new RegExp(`doc=${publicDocId}`));
  let releaseDelayed!: () => void;
  let markFetchStarted!: () => void;
  const fetchStarted = new Promise<void>(resolve => { markFetchStarted = resolve; });
  const delayedResponse = new Promise<void>(resolve => { releaseDelayed = resolve; });
  await page.route(`**/api/documents/${delayedDocId}`, async route => {
    const response = await route.fetch();
    markFetchStarted();
    await delayedResponse;
    await route.fulfill({ response });
  });
  page.once("dialog", dialog => dialog.accept());
  await page.locator(".document-link").filter({ hasText: "延迟响应目标" }).click();
  await fetchStarted;
  page.once("dialog", dialog => dialog.accept());
  await page.getByRole("button", { name: "退出登录" }).click();
  await expect(page.getByRole("heading", { name: "欢迎回来" })).toBeVisible();
  releaseDelayed();
  await expect(page.getByRole("heading", { name: "欢迎回来" })).toBeVisible();
  await expect(page.getByText("登出竞态的目标文档。")).toHaveCount(0);
  const remainingDrafts = await page.evaluate(() => Object.keys(sessionStorage).filter(key => key.startsWith("teamshelf:draft:")));
  expect(remainingDrafts).toEqual([]);
  await viewerContext.close();
});
